/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package rec.everis.forms.service.service.base;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Reference;

import rec.everis.forms.service.model.MaintenanceActivityForms;
import rec.everis.forms.service.service.MaintenanceActivityFormsLocalService;
import rec.everis.forms.service.service.persistence.MaintenanceActivityFormsPersistence;

/**
 * Provides the base implementation for the maintenance activity forms local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link rec.everis.forms.service.service.impl.MaintenanceActivityFormsLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see rec.everis.forms.service.service.impl.MaintenanceActivityFormsLocalServiceImpl
 * @generated
 */
public abstract class MaintenanceActivityFormsLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService,
			   MaintenanceActivityFormsLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>MaintenanceActivityFormsLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>rec.everis.forms.service.service.MaintenanceActivityFormsLocalServiceUtil</code>.
	 */

	/**
	 * Adds the maintenance activity forms to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect MaintenanceActivityFormsLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param maintenanceActivityForms the maintenance activity forms
	 * @return the maintenance activity forms that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public MaintenanceActivityForms addMaintenanceActivityForms(
		MaintenanceActivityForms maintenanceActivityForms) {

		maintenanceActivityForms.setNew(true);

		return maintenanceActivityFormsPersistence.update(
			maintenanceActivityForms);
	}

	/**
	 * Creates a new maintenance activity forms with the primary key. Does not add the maintenance activity forms to the database.
	 *
	 * @param maintenanceactivityformId the primary key for the new maintenance activity forms
	 * @return the new maintenance activity forms
	 */
	@Override
	@Transactional(enabled = false)
	public MaintenanceActivityForms createMaintenanceActivityForms(
		long maintenanceactivityformId) {

		return maintenanceActivityFormsPersistence.create(
			maintenanceactivityformId);
	}

	/**
	 * Deletes the maintenance activity forms with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect MaintenanceActivityFormsLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param maintenanceactivityformId the primary key of the maintenance activity forms
	 * @return the maintenance activity forms that was removed
	 * @throws PortalException if a maintenance activity forms with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public MaintenanceActivityForms deleteMaintenanceActivityForms(
			long maintenanceactivityformId)
		throws PortalException {

		return maintenanceActivityFormsPersistence.remove(
			maintenanceactivityformId);
	}

	/**
	 * Deletes the maintenance activity forms from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect MaintenanceActivityFormsLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param maintenanceActivityForms the maintenance activity forms
	 * @return the maintenance activity forms that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public MaintenanceActivityForms deleteMaintenanceActivityForms(
		MaintenanceActivityForms maintenanceActivityForms) {

		return maintenanceActivityFormsPersistence.remove(
			maintenanceActivityForms);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			MaintenanceActivityForms.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return maintenanceActivityFormsPersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>rec.everis.forms.service.model.impl.MaintenanceActivityFormsModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return maintenanceActivityFormsPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>rec.everis.forms.service.model.impl.MaintenanceActivityFormsModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return maintenanceActivityFormsPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return maintenanceActivityFormsPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return maintenanceActivityFormsPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public MaintenanceActivityForms fetchMaintenanceActivityForms(
		long maintenanceactivityformId) {

		return maintenanceActivityFormsPersistence.fetchByPrimaryKey(
			maintenanceactivityformId);
	}

	/**
	 * Returns the maintenance activity forms matching the UUID and group.
	 *
	 * @param uuid the maintenance activity forms's UUID
	 * @param groupId the primary key of the group
	 * @return the matching maintenance activity forms, or <code>null</code> if a matching maintenance activity forms could not be found
	 */
	@Override
	public MaintenanceActivityForms
		fetchMaintenanceActivityFormsByUuidAndGroupId(
			String uuid, long groupId) {

		return maintenanceActivityFormsPersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the maintenance activity forms with the primary key.
	 *
	 * @param maintenanceactivityformId the primary key of the maintenance activity forms
	 * @return the maintenance activity forms
	 * @throws PortalException if a maintenance activity forms with the primary key could not be found
	 */
	@Override
	public MaintenanceActivityForms getMaintenanceActivityForms(
			long maintenanceactivityformId)
		throws PortalException {

		return maintenanceActivityFormsPersistence.findByPrimaryKey(
			maintenanceactivityformId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			maintenanceActivityFormsLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(MaintenanceActivityForms.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"maintenanceactivityformId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			maintenanceActivityFormsLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			MaintenanceActivityForms.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"maintenanceactivityformId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			maintenanceActivityFormsLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(MaintenanceActivityForms.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"maintenanceactivityformId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod
				<MaintenanceActivityForms>() {

				@Override
				public void performAction(
						MaintenanceActivityForms maintenanceActivityForms)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, maintenanceActivityForms);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(
					MaintenanceActivityForms.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return maintenanceActivityFormsPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return maintenanceActivityFormsLocalService.
			deleteMaintenanceActivityForms(
				(MaintenanceActivityForms)persistedModel);
	}

	public BasePersistence<MaintenanceActivityForms> getBasePersistence() {
		return maintenanceActivityFormsPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return maintenanceActivityFormsPersistence.findByPrimaryKey(
			primaryKeyObj);
	}

	/**
	 * Returns all the maintenance activity formses matching the UUID and company.
	 *
	 * @param uuid the UUID of the maintenance activity formses
	 * @param companyId the primary key of the company
	 * @return the matching maintenance activity formses, or an empty list if no matches were found
	 */
	@Override
	public List<MaintenanceActivityForms>
		getMaintenanceActivityFormsesByUuidAndCompanyId(
			String uuid, long companyId) {

		return maintenanceActivityFormsPersistence.findByUuid_C(
			uuid, companyId);
	}

	/**
	 * Returns a range of maintenance activity formses matching the UUID and company.
	 *
	 * @param uuid the UUID of the maintenance activity formses
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of maintenance activity formses
	 * @param end the upper bound of the range of maintenance activity formses (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching maintenance activity formses, or an empty list if no matches were found
	 */
	@Override
	public List<MaintenanceActivityForms>
		getMaintenanceActivityFormsesByUuidAndCompanyId(
			String uuid, long companyId, int start, int end,
			OrderByComparator<MaintenanceActivityForms> orderByComparator) {

		return maintenanceActivityFormsPersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the maintenance activity forms matching the UUID and group.
	 *
	 * @param uuid the maintenance activity forms's UUID
	 * @param groupId the primary key of the group
	 * @return the matching maintenance activity forms
	 * @throws PortalException if a matching maintenance activity forms could not be found
	 */
	@Override
	public MaintenanceActivityForms getMaintenanceActivityFormsByUuidAndGroupId(
			String uuid, long groupId)
		throws PortalException {

		return maintenanceActivityFormsPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the maintenance activity formses.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>rec.everis.forms.service.model.impl.MaintenanceActivityFormsModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of maintenance activity formses
	 * @param end the upper bound of the range of maintenance activity formses (not inclusive)
	 * @return the range of maintenance activity formses
	 */
	@Override
	public List<MaintenanceActivityForms> getMaintenanceActivityFormses(
		int start, int end) {

		return maintenanceActivityFormsPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of maintenance activity formses.
	 *
	 * @return the number of maintenance activity formses
	 */
	@Override
	public int getMaintenanceActivityFormsesCount() {
		return maintenanceActivityFormsPersistence.countAll();
	}

	/**
	 * Updates the maintenance activity forms in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect MaintenanceActivityFormsLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param maintenanceActivityForms the maintenance activity forms
	 * @return the maintenance activity forms that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public MaintenanceActivityForms updateMaintenanceActivityForms(
		MaintenanceActivityForms maintenanceActivityForms) {

		return maintenanceActivityFormsPersistence.update(
			maintenanceActivityForms);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			MaintenanceActivityFormsLocalService.class,
			IdentifiableOSGiService.class, PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		maintenanceActivityFormsLocalService =
			(MaintenanceActivityFormsLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return MaintenanceActivityFormsLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return MaintenanceActivityForms.class;
	}

	protected String getModelClassName() {
		return MaintenanceActivityForms.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				maintenanceActivityFormsPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	protected MaintenanceActivityFormsLocalService
		maintenanceActivityFormsLocalService;

	@Reference
	protected MaintenanceActivityFormsPersistence
		maintenanceActivityFormsPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}