/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package rec.everis.forms.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the MaintenanceActivityForms service. Represents a row in the &quot;AMAF_MaintenanceActivityForms&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>rec.everis.forms.service.model.impl.MaintenanceActivityFormsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>rec.everis.forms.service.model.impl.MaintenanceActivityFormsImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MaintenanceActivityForms
 * @generated
 */
@ProviderType
public interface MaintenanceActivityFormsModel
	extends BaseModel<MaintenanceActivityForms>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a maintenance activity forms model instance should use the {@link MaintenanceActivityForms} interface instead.
	 */

	/**
	 * Returns the primary key of this maintenance activity forms.
	 *
	 * @return the primary key of this maintenance activity forms
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this maintenance activity forms.
	 *
	 * @param primaryKey the primary key of this maintenance activity forms
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this maintenance activity forms.
	 *
	 * @return the uuid of this maintenance activity forms
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this maintenance activity forms.
	 *
	 * @param uuid the uuid of this maintenance activity forms
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the maintenanceactivityform ID of this maintenance activity forms.
	 *
	 * @return the maintenanceactivityform ID of this maintenance activity forms
	 */
	public long getMaintenanceactivityformId();

	/**
	 * Sets the maintenanceactivityform ID of this maintenance activity forms.
	 *
	 * @param maintenanceactivityformId the maintenanceactivityform ID of this maintenance activity forms
	 */
	public void setMaintenanceactivityformId(long maintenanceactivityformId);

	/**
	 * Returns the group ID of this maintenance activity forms.
	 *
	 * @return the group ID of this maintenance activity forms
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this maintenance activity forms.
	 *
	 * @param groupId the group ID of this maintenance activity forms
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this maintenance activity forms.
	 *
	 * @return the company ID of this maintenance activity forms
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this maintenance activity forms.
	 *
	 * @param companyId the company ID of this maintenance activity forms
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this maintenance activity forms.
	 *
	 * @return the user ID of this maintenance activity forms
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this maintenance activity forms.
	 *
	 * @param userId the user ID of this maintenance activity forms
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this maintenance activity forms.
	 *
	 * @return the user uuid of this maintenance activity forms
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this maintenance activity forms.
	 *
	 * @param userUuid the user uuid of this maintenance activity forms
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this maintenance activity forms.
	 *
	 * @return the user name of this maintenance activity forms
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this maintenance activity forms.
	 *
	 * @param userName the user name of this maintenance activity forms
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this maintenance activity forms.
	 *
	 * @return the create date of this maintenance activity forms
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this maintenance activity forms.
	 *
	 * @param createDate the create date of this maintenance activity forms
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this maintenance activity forms.
	 *
	 * @return the modified date of this maintenance activity forms
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this maintenance activity forms.
	 *
	 * @param modifiedDate the modified date of this maintenance activity forms
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the form type of this maintenance activity forms.
	 *
	 * @return the form type of this maintenance activity forms
	 */
	@AutoEscape
	public String getFormType();

	/**
	 * Sets the form type of this maintenance activity forms.
	 *
	 * @param formType the form type of this maintenance activity forms
	 */
	public void setFormType(String formType);

	/**
	 * Returns the year of this maintenance activity forms.
	 *
	 * @return the year of this maintenance activity forms
	 */
	public int getYear();

	/**
	 * Sets the year of this maintenance activity forms.
	 *
	 * @param year the year of this maintenance activity forms
	 */
	public void setYear(int year);

	/**
	 * Returns the submit date of this maintenance activity forms.
	 *
	 * @return the submit date of this maintenance activity forms
	 */
	public Date getSubmitDate();

	/**
	 * Sets the submit date of this maintenance activity forms.
	 *
	 * @param submitDate the submit date of this maintenance activity forms
	 */
	public void setSubmitDate(Date submitDate);

	/**
	 * Returns the approval date of this maintenance activity forms.
	 *
	 * @return the approval date of this maintenance activity forms
	 */
	public Date getApprovalDate();

	/**
	 * Sets the approval date of this maintenance activity forms.
	 *
	 * @param approvalDate the approval date of this maintenance activity forms
	 */
	public void setApprovalDate(Date approvalDate);

	/**
	 * Returns the submit date formatted of this maintenance activity forms.
	 *
	 * @return the submit date formatted of this maintenance activity forms
	 */
	@AutoEscape
	public String getSubmitDateFormatted();

	/**
	 * Sets the submit date formatted of this maintenance activity forms.
	 *
	 * @param submitDateFormatted the submit date formatted of this maintenance activity forms
	 */
	public void setSubmitDateFormatted(String submitDateFormatted);

	/**
	 * Returns the approval date formatted of this maintenance activity forms.
	 *
	 * @return the approval date formatted of this maintenance activity forms
	 */
	@AutoEscape
	public String getApprovalDateFormatted();

	/**
	 * Sets the approval date formatted of this maintenance activity forms.
	 *
	 * @param approvalDateFormatted the approval date formatted of this maintenance activity forms
	 */
	public void setApprovalDateFormatted(String approvalDateFormatted);

	/**
	 * Returns the status of this maintenance activity forms.
	 *
	 * @return the status of this maintenance activity forms
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this maintenance activity forms.
	 *
	 * @param status the status of this maintenance activity forms
	 */
	public void setStatus(String status);

	/**
	 * Returns the form instance record version ID of this maintenance activity forms.
	 *
	 * @return the form instance record version ID of this maintenance activity forms
	 */
	public long getFormInstanceRecordVersionId();

	/**
	 * Sets the form instance record version ID of this maintenance activity forms.
	 *
	 * @param formInstanceRecordVersionId the form instance record version ID of this maintenance activity forms
	 */
	public void setFormInstanceRecordVersionId(
		long formInstanceRecordVersionId);

	/**
	 * Returns the org site ID of this maintenance activity forms.
	 *
	 * @return the org site ID of this maintenance activity forms
	 */
	public long getOrgSiteId();

	/**
	 * Sets the org site ID of this maintenance activity forms.
	 *
	 * @param orgSiteId the org site ID of this maintenance activity forms
	 */
	public void setOrgSiteId(long orgSiteId);

	/**
	 * Returns the view url of this maintenance activity forms.
	 *
	 * @return the view url of this maintenance activity forms
	 */
	@AutoEscape
	public String getViewUrl();

	/**
	 * Sets the view url of this maintenance activity forms.
	 *
	 * @param viewUrl the view url of this maintenance activity forms
	 */
	public void setViewUrl(String viewUrl);

	/**
	 * Returns the form instance ID of this maintenance activity forms.
	 *
	 * @return the form instance ID of this maintenance activity forms
	 */
	public long getFormInstanceId();

	/**
	 * Sets the form instance ID of this maintenance activity forms.
	 *
	 * @param formInstanceId the form instance ID of this maintenance activity forms
	 */
	public void setFormInstanceId(long formInstanceId);

	/**
	 * Returns the form instance record ID of this maintenance activity forms.
	 *
	 * @return the form instance record ID of this maintenance activity forms
	 */
	public long getFormInstanceRecordId();

	/**
	 * Sets the form instance record ID of this maintenance activity forms.
	 *
	 * @param formInstanceRecordId the form instance record ID of this maintenance activity forms
	 */
	public void setFormInstanceRecordId(long formInstanceRecordId);

}