/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.everis.rec.remediation.tracker.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the RemediationTracker service. Represents a row in the &quot;REC_RemediationTracker&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.everis.rec.remediation.tracker.model.impl.RemediationTrackerModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.everis.rec.remediation.tracker.model.impl.RemediationTrackerImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RemediationTracker
 * @generated
 */
@ProviderType
public interface RemediationTrackerModel
	extends BaseModel<RemediationTracker>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a remediation tracker model instance should use the {@link RemediationTracker} interface instead.
	 */

	/**
	 * Returns the primary key of this remediation tracker.
	 *
	 * @return the primary key of this remediation tracker
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this remediation tracker.
	 *
	 * @param primaryKey the primary key of this remediation tracker
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this remediation tracker.
	 *
	 * @return the uuid of this remediation tracker
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this remediation tracker.
	 *
	 * @param uuid the uuid of this remediation tracker
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the remediation tracker ID of this remediation tracker.
	 *
	 * @return the remediation tracker ID of this remediation tracker
	 */
	public long getRemediationTrackerId();

	/**
	 * Sets the remediation tracker ID of this remediation tracker.
	 *
	 * @param remediationTrackerId the remediation tracker ID of this remediation tracker
	 */
	public void setRemediationTrackerId(long remediationTrackerId);

	/**
	 * Returns the group ID of this remediation tracker.
	 *
	 * @return the group ID of this remediation tracker
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this remediation tracker.
	 *
	 * @param groupId the group ID of this remediation tracker
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this remediation tracker.
	 *
	 * @return the company ID of this remediation tracker
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this remediation tracker.
	 *
	 * @param companyId the company ID of this remediation tracker
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this remediation tracker.
	 *
	 * @return the user ID of this remediation tracker
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this remediation tracker.
	 *
	 * @param userId the user ID of this remediation tracker
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this remediation tracker.
	 *
	 * @return the user uuid of this remediation tracker
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this remediation tracker.
	 *
	 * @param userUuid the user uuid of this remediation tracker
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this remediation tracker.
	 *
	 * @return the user name of this remediation tracker
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this remediation tracker.
	 *
	 * @param userName the user name of this remediation tracker
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this remediation tracker.
	 *
	 * @return the create date of this remediation tracker
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this remediation tracker.
	 *
	 * @param createDate the create date of this remediation tracker
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this remediation tracker.
	 *
	 * @return the modified date of this remediation tracker
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this remediation tracker.
	 *
	 * @param modifiedDate the modified date of this remediation tracker
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the title of this remediation tracker.
	 *
	 * @return the title of this remediation tracker
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this remediation tracker.
	 *
	 * @param title the title of this remediation tracker
	 */
	public void setTitle(String title);

	/**
	 * Returns the org site ID of this remediation tracker.
	 *
	 * @return the org site ID of this remediation tracker
	 */
	public long getOrgSiteId();

	/**
	 * Sets the org site ID of this remediation tracker.
	 *
	 * @param orgSiteId the org site ID of this remediation tracker
	 */
	public void setOrgSiteId(long orgSiteId);

	/**
	 * Returns the specific party of this remediation tracker.
	 *
	 * @return the specific party of this remediation tracker
	 */
	@AutoEscape
	public String getSpecificParty();

	/**
	 * Sets the specific party of this remediation tracker.
	 *
	 * @param specificParty the specific party of this remediation tracker
	 */
	public void setSpecificParty(String specificParty);

	/**
	 * Returns the category of this remediation tracker.
	 *
	 * @return the category of this remediation tracker
	 */
	@AutoEscape
	public String getCategory();

	/**
	 * Sets the category of this remediation tracker.
	 *
	 * @param category the category of this remediation tracker
	 */
	public void setCategory(String category);

	/**
	 * Returns the description of this remediation tracker.
	 *
	 * @return the description of this remediation tracker
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this remediation tracker.
	 *
	 * @param description the description of this remediation tracker
	 */
	public void setDescription(String description);

	/**
	 * Returns the due date of this remediation tracker.
	 *
	 * @return the due date of this remediation tracker
	 */
	@AutoEscape
	public String getDueDate();

	/**
	 * Sets the due date of this remediation tracker.
	 *
	 * @param dueDate the due date of this remediation tracker
	 */
	public void setDueDate(String dueDate);

	/**
	 * Returns the due date formated of this remediation tracker.
	 *
	 * @return the due date formated of this remediation tracker
	 */
	public Date getDueDateFormated();

	/**
	 * Sets the due date formated of this remediation tracker.
	 *
	 * @param dueDateFormated the due date formated of this remediation tracker
	 */
	public void setDueDateFormated(Date dueDateFormated);

	/**
	 * Returns the status of this remediation tracker.
	 *
	 * @return the status of this remediation tracker
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this remediation tracker.
	 *
	 * @param status the status of this remediation tracker
	 */
	public void setStatus(String status);

	/**
	 * Returns the calendar booking ID of this remediation tracker.
	 *
	 * @return the calendar booking ID of this remediation tracker
	 */
	public long getCalendarBookingId();

	/**
	 * Sets the calendar booking ID of this remediation tracker.
	 *
	 * @param calendarBookingId the calendar booking ID of this remediation tracker
	 */
	public void setCalendarBookingId(long calendarBookingId);

}