/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package rec.link.menu.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import rec.link.menu.model.LinkMenu;
import rec.link.menu.model.LinkMenuModel;
import rec.link.menu.model.LinkMenuSoap;

/**
 * The base model implementation for the LinkMenu service. Represents a row in the &quot;LinkMenu_LinkMenu&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>LinkMenuModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LinkMenuImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LinkMenuImpl
 * @generated
 */
@JSON(strict = true)
public class LinkMenuModelImpl
	extends BaseModelImpl<LinkMenu> implements LinkMenuModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a link menu model instance should use the <code>LinkMenu</code> interface instead.
	 */
	public static final String TABLE_NAME = "LinkMenu_LinkMenu";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"linkId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"linkName", Types.VARCHAR}, {"link", Types.VARCHAR},
		{"linkPosition", Types.INTEGER}, {"iconName", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("linkId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("linkName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("link", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("linkPosition", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("iconName", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table LinkMenu_LinkMenu (uuid_ VARCHAR(75) null,linkId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,linkName VARCHAR(75) null,link VARCHAR(75) null,linkPosition INTEGER,iconName VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table LinkMenu_LinkMenu";

	public static final String ORDER_BY_JPQL =
		" ORDER BY linkMenu.linkPosition ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY LinkMenu_LinkMenu.linkPosition ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)
	 */
	@Deprecated
	public static final long LINKPOSITION_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static LinkMenu toModel(LinkMenuSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		LinkMenu model = new LinkMenuImpl();

		model.setUuid(soapModel.getUuid());
		model.setLinkId(soapModel.getLinkId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setLinkName(soapModel.getLinkName());
		model.setLink(soapModel.getLink());
		model.setLinkPosition(soapModel.getLinkPosition());
		model.setIconName(soapModel.getIconName());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<LinkMenu> toModels(LinkMenuSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<LinkMenu> models = new ArrayList<LinkMenu>(soapModels.length);

		for (LinkMenuSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public LinkMenuModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _linkId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLinkId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _linkId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LinkMenu.class;
	}

	@Override
	public String getModelClassName() {
		return LinkMenu.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<LinkMenu, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<LinkMenu, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LinkMenu, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((LinkMenu)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<LinkMenu, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<LinkMenu, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(LinkMenu)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<LinkMenu, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<LinkMenu, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, LinkMenu>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			LinkMenu.class.getClassLoader(), LinkMenu.class,
			ModelWrapper.class);

		try {
			Constructor<LinkMenu> constructor =
				(Constructor<LinkMenu>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<LinkMenu, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<LinkMenu, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<LinkMenu, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<LinkMenu, Object>>();
		Map<String, BiConsumer<LinkMenu, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<LinkMenu, ?>>();

		attributeGetterFunctions.put("uuid", LinkMenu::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<LinkMenu, String>)LinkMenu::setUuid);
		attributeGetterFunctions.put("linkId", LinkMenu::getLinkId);
		attributeSetterBiConsumers.put(
			"linkId", (BiConsumer<LinkMenu, Long>)LinkMenu::setLinkId);
		attributeGetterFunctions.put("groupId", LinkMenu::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<LinkMenu, Long>)LinkMenu::setGroupId);
		attributeGetterFunctions.put("companyId", LinkMenu::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<LinkMenu, Long>)LinkMenu::setCompanyId);
		attributeGetterFunctions.put("userId", LinkMenu::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<LinkMenu, Long>)LinkMenu::setUserId);
		attributeGetterFunctions.put("userName", LinkMenu::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<LinkMenu, String>)LinkMenu::setUserName);
		attributeGetterFunctions.put("createDate", LinkMenu::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<LinkMenu, Date>)LinkMenu::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", LinkMenu::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<LinkMenu, Date>)LinkMenu::setModifiedDate);
		attributeGetterFunctions.put("linkName", LinkMenu::getLinkName);
		attributeSetterBiConsumers.put(
			"linkName", (BiConsumer<LinkMenu, String>)LinkMenu::setLinkName);
		attributeGetterFunctions.put("link", LinkMenu::getLink);
		attributeSetterBiConsumers.put(
			"link", (BiConsumer<LinkMenu, String>)LinkMenu::setLink);
		attributeGetterFunctions.put("linkPosition", LinkMenu::getLinkPosition);
		attributeSetterBiConsumers.put(
			"linkPosition",
			(BiConsumer<LinkMenu, Integer>)LinkMenu::setLinkPosition);
		attributeGetterFunctions.put("iconName", LinkMenu::getIconName);
		attributeSetterBiConsumers.put(
			"iconName", (BiConsumer<LinkMenu, String>)LinkMenu::setIconName);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getLinkId() {
		return _linkId;
	}

	@Override
	public void setLinkId(long linkId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_linkId = linkId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getLinkName() {
		if (_linkName == null) {
			return "";
		}
		else {
			return _linkName;
		}
	}

	@Override
	public void setLinkName(String linkName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_linkName = linkName;
	}

	@JSON
	@Override
	public String getLink() {
		if (_link == null) {
			return "";
		}
		else {
			return _link;
		}
	}

	@Override
	public void setLink(String link) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_link = link;
	}

	@JSON
	@Override
	public int getLinkPosition() {
		return _linkPosition;
	}

	@Override
	public void setLinkPosition(int linkPosition) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_linkPosition = linkPosition;
	}

	@JSON
	@Override
	public String getIconName() {
		if (_iconName == null) {
			return "";
		}
		else {
			return _iconName;
		}
	}

	@Override
	public void setIconName(String iconName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_iconName = iconName;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(LinkMenu.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (entry.getValue() != getColumnValue(entry.getKey())) {
				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), LinkMenu.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public LinkMenu toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, LinkMenu>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LinkMenuImpl linkMenuImpl = new LinkMenuImpl();

		linkMenuImpl.setUuid(getUuid());
		linkMenuImpl.setLinkId(getLinkId());
		linkMenuImpl.setGroupId(getGroupId());
		linkMenuImpl.setCompanyId(getCompanyId());
		linkMenuImpl.setUserId(getUserId());
		linkMenuImpl.setUserName(getUserName());
		linkMenuImpl.setCreateDate(getCreateDate());
		linkMenuImpl.setModifiedDate(getModifiedDate());
		linkMenuImpl.setLinkName(getLinkName());
		linkMenuImpl.setLink(getLink());
		linkMenuImpl.setLinkPosition(getLinkPosition());
		linkMenuImpl.setIconName(getIconName());

		linkMenuImpl.resetOriginalValues();

		return linkMenuImpl;
	}

	@Override
	public int compareTo(LinkMenu linkMenu) {
		int value = 0;

		if (getLinkPosition() < linkMenu.getLinkPosition()) {
			value = -1;
		}
		else if (getLinkPosition() > linkMenu.getLinkPosition()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof LinkMenu)) {
			return false;
		}

		LinkMenu linkMenu = (LinkMenu)object;

		long primaryKey = linkMenu.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<LinkMenu> toCacheModel() {
		LinkMenuCacheModel linkMenuCacheModel = new LinkMenuCacheModel();

		linkMenuCacheModel.uuid = getUuid();

		String uuid = linkMenuCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			linkMenuCacheModel.uuid = null;
		}

		linkMenuCacheModel.linkId = getLinkId();

		linkMenuCacheModel.groupId = getGroupId();

		linkMenuCacheModel.companyId = getCompanyId();

		linkMenuCacheModel.userId = getUserId();

		linkMenuCacheModel.userName = getUserName();

		String userName = linkMenuCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			linkMenuCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			linkMenuCacheModel.createDate = createDate.getTime();
		}
		else {
			linkMenuCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			linkMenuCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			linkMenuCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		linkMenuCacheModel.linkName = getLinkName();

		String linkName = linkMenuCacheModel.linkName;

		if ((linkName != null) && (linkName.length() == 0)) {
			linkMenuCacheModel.linkName = null;
		}

		linkMenuCacheModel.link = getLink();

		String link = linkMenuCacheModel.link;

		if ((link != null) && (link.length() == 0)) {
			linkMenuCacheModel.link = null;
		}

		linkMenuCacheModel.linkPosition = getLinkPosition();

		linkMenuCacheModel.iconName = getIconName();

		String iconName = linkMenuCacheModel.iconName;

		if ((iconName != null) && (iconName.length() == 0)) {
			linkMenuCacheModel.iconName = null;
		}

		return linkMenuCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<LinkMenu, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<LinkMenu, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LinkMenu, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((LinkMenu)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<LinkMenu, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<LinkMenu, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LinkMenu, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((LinkMenu)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, LinkMenu>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private long _linkId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _linkName;
	private String _link;
	private int _linkPosition;
	private String _iconName;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<LinkMenu, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((LinkMenu)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("linkId", _linkId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("linkName", _linkName);
		_columnOriginalValues.put("link", _link);
		_columnOriginalValues.put("linkPosition", _linkPosition);
		_columnOriginalValues.put("iconName", _iconName);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("linkId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("linkName", 256L);

		columnBitmasks.put("link", 512L);

		columnBitmasks.put("linkPosition", 1024L);

		columnBitmasks.put("iconName", 2048L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private LinkMenu _escapedModel;

}