/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package rec.supporting.resources.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the supportR service. Represents a row in the &quot;RECsr_supportR&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>rec.supporting.resources.model.impl.supportRModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>rec.supporting.resources.model.impl.supportRImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see supportR
 * @generated
 */
@ProviderType
public interface supportRModel
	extends BaseModel<supportR>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a support r model instance should use the {@link supportR} interface instead.
	 */

	/**
	 * Returns the primary key of this support r.
	 *
	 * @return the primary key of this support r
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this support r.
	 *
	 * @param primaryKey the primary key of this support r
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this support r.
	 *
	 * @return the uuid of this support r
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this support r.
	 *
	 * @param uuid the uuid of this support r
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the support r ID of this support r.
	 *
	 * @return the support r ID of this support r
	 */
	public long getSupportRId();

	/**
	 * Sets the support r ID of this support r.
	 *
	 * @param supportRId the support r ID of this support r
	 */
	public void setSupportRId(long supportRId);

	/**
	 * Returns the group ID of this support r.
	 *
	 * @return the group ID of this support r
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this support r.
	 *
	 * @param groupId the group ID of this support r
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this support r.
	 *
	 * @return the company ID of this support r
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this support r.
	 *
	 * @param companyId the company ID of this support r
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this support r.
	 *
	 * @return the user ID of this support r
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this support r.
	 *
	 * @param userId the user ID of this support r
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this support r.
	 *
	 * @return the user uuid of this support r
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this support r.
	 *
	 * @param userUuid the user uuid of this support r
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this support r.
	 *
	 * @return the user name of this support r
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this support r.
	 *
	 * @param userName the user name of this support r
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this support r.
	 *
	 * @return the create date of this support r
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this support r.
	 *
	 * @param createDate the create date of this support r
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this support r.
	 *
	 * @return the modified date of this support r
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this support r.
	 *
	 * @param modifiedDate the modified date of this support r
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the specific party of this support r.
	 *
	 * @return the specific party of this support r
	 */
	@AutoEscape
	public String getSpecificParty();

	/**
	 * Sets the specific party of this support r.
	 *
	 * @param specificParty the specific party of this support r
	 */
	public void setSpecificParty(String specificParty);

	/**
	 * Returns the org site ID of this support r.
	 *
	 * @return the org site ID of this support r
	 */
	public long getOrgSiteId();

	/**
	 * Sets the org site ID of this support r.
	 *
	 * @param orgSiteId the org site ID of this support r
	 */
	public void setOrgSiteId(long orgSiteId);

	/**
	 * Returns the type of this support r.
	 *
	 * @return the type of this support r
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this support r.
	 *
	 * @param type the type of this support r
	 */
	public void setType(String type);

	/**
	 * Returns the title of this support r.
	 *
	 * @return the title of this support r
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this support r.
	 *
	 * @param title the title of this support r
	 */
	public void setTitle(String title);

	/**
	 * Returns the description of this support r.
	 *
	 * @return the description of this support r
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this support r.
	 *
	 * @param description the description of this support r
	 */
	public void setDescription(String description);

	/**
	 * Returns the due date of this support r.
	 *
	 * @return the due date of this support r
	 */
	public Date getDueDate();

	/**
	 * Sets the due date of this support r.
	 *
	 * @param dueDate the due date of this support r
	 */
	public void setDueDate(Date dueDate);

	/**
	 * Returns the status of this support r.
	 *
	 * @return the status of this support r
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this support r.
	 *
	 * @param status the status of this support r
	 */
	public void setStatus(String status);

	/**
	 * Returns the link of this support r.
	 *
	 * @return the link of this support r
	 */
	@AutoEscape
	public String getLink();

	/**
	 * Sets the link of this support r.
	 *
	 * @param link the link of this support r
	 */
	public void setLink(String link);

	/**
	 * Returns the display link of this support r.
	 *
	 * @return the display link of this support r
	 */
	@AutoEscape
	public String getDisplayLink();

	/**
	 * Sets the display link of this support r.
	 *
	 * @param displayLink the display link of this support r
	 */
	public void setDisplayLink(String displayLink);

	/**
	 * Returns the calendar booking ID of this support r.
	 *
	 * @return the calendar booking ID of this support r
	 */
	public long getCalendarBookingId();

	/**
	 * Sets the calendar booking ID of this support r.
	 *
	 * @param calendarBookingId the calendar booking ID of this support r
	 */
	public void setCalendarBookingId(long calendarBookingId);

}