/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package rec.supporting.resources.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import rec.supporting.resources.model.supportR;
import rec.supporting.resources.model.supportRModel;
import rec.supporting.resources.model.supportRSoap;

/**
 * The base model implementation for the supportR service. Represents a row in the &quot;RECsr_supportR&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>supportRModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link supportRImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see supportRImpl
 * @generated
 */
@JSON(strict = true)
public class supportRModelImpl
	extends BaseModelImpl<supportR> implements supportRModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a support r model instance should use the <code>supportR</code> interface instead.
	 */
	public static final String TABLE_NAME = "RECsr_supportR";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"supportRId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"specificParty", Types.VARCHAR}, {"orgSiteId", Types.BIGINT},
		{"type_", Types.VARCHAR}, {"title", Types.VARCHAR},
		{"description", Types.VARCHAR}, {"dueDate", Types.TIMESTAMP},
		{"status", Types.VARCHAR}, {"link", Types.VARCHAR},
		{"displayLink", Types.VARCHAR}, {"calendarBookingId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("supportRId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("specificParty", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("orgSiteId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("type_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("title", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("dueDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("link", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("displayLink", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("calendarBookingId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table RECsr_supportR (uuid_ VARCHAR(75) null,supportRId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,specificParty VARCHAR(75) null,orgSiteId LONG,type_ VARCHAR(75) null,title VARCHAR(250) null,description VARCHAR(500) null,dueDate DATE null,status VARCHAR(75) null,link VARCHAR(1000) null,displayLink VARCHAR(75) null,calendarBookingId LONG)";

	public static final String TABLE_SQL_DROP = "drop table RECsr_supportR";

	public static final String ORDER_BY_JPQL =
		" ORDER BY supportR.createDate ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY RECsr_supportR.createDate ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long CREATEDATE_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long DUEDATE_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long LINK_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long STATUS_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long TITLE_COLUMN_BITMASK = 64L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long TYPE_COLUMN_BITMASK = 128L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 256L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static supportR toModel(supportRSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		supportR model = new supportRImpl();

		model.setUuid(soapModel.getUuid());
		model.setSupportRId(soapModel.getSupportRId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setSpecificParty(soapModel.getSpecificParty());
		model.setOrgSiteId(soapModel.getOrgSiteId());
		model.setType(soapModel.getType());
		model.setTitle(soapModel.getTitle());
		model.setDescription(soapModel.getDescription());
		model.setDueDate(soapModel.getDueDate());
		model.setStatus(soapModel.getStatus());
		model.setLink(soapModel.getLink());
		model.setDisplayLink(soapModel.getDisplayLink());
		model.setCalendarBookingId(soapModel.getCalendarBookingId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<supportR> toModels(supportRSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<supportR> models = new ArrayList<supportR>(soapModels.length);

		for (supportRSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public supportRModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _supportRId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSupportRId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _supportRId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return supportR.class;
	}

	@Override
	public String getModelClassName() {
		return supportR.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<supportR, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<supportR, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<supportR, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((supportR)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<supportR, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<supportR, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(supportR)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<supportR, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<supportR, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, supportR>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			supportR.class.getClassLoader(), supportR.class,
			ModelWrapper.class);

		try {
			Constructor<supportR> constructor =
				(Constructor<supportR>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<supportR, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<supportR, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<supportR, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<supportR, Object>>();
		Map<String, BiConsumer<supportR, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<supportR, ?>>();

		attributeGetterFunctions.put("uuid", supportR::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<supportR, String>)supportR::setUuid);
		attributeGetterFunctions.put("supportRId", supportR::getSupportRId);
		attributeSetterBiConsumers.put(
			"supportRId", (BiConsumer<supportR, Long>)supportR::setSupportRId);
		attributeGetterFunctions.put("groupId", supportR::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<supportR, Long>)supportR::setGroupId);
		attributeGetterFunctions.put("companyId", supportR::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<supportR, Long>)supportR::setCompanyId);
		attributeGetterFunctions.put("userId", supportR::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<supportR, Long>)supportR::setUserId);
		attributeGetterFunctions.put("userName", supportR::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<supportR, String>)supportR::setUserName);
		attributeGetterFunctions.put("createDate", supportR::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<supportR, Date>)supportR::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", supportR::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<supportR, Date>)supportR::setModifiedDate);
		attributeGetterFunctions.put(
			"specificParty", supportR::getSpecificParty);
		attributeSetterBiConsumers.put(
			"specificParty",
			(BiConsumer<supportR, String>)supportR::setSpecificParty);
		attributeGetterFunctions.put("orgSiteId", supportR::getOrgSiteId);
		attributeSetterBiConsumers.put(
			"orgSiteId", (BiConsumer<supportR, Long>)supportR::setOrgSiteId);
		attributeGetterFunctions.put("type", supportR::getType);
		attributeSetterBiConsumers.put(
			"type", (BiConsumer<supportR, String>)supportR::setType);
		attributeGetterFunctions.put("title", supportR::getTitle);
		attributeSetterBiConsumers.put(
			"title", (BiConsumer<supportR, String>)supportR::setTitle);
		attributeGetterFunctions.put("description", supportR::getDescription);
		attributeSetterBiConsumers.put(
			"description",
			(BiConsumer<supportR, String>)supportR::setDescription);
		attributeGetterFunctions.put("dueDate", supportR::getDueDate);
		attributeSetterBiConsumers.put(
			"dueDate", (BiConsumer<supportR, Date>)supportR::setDueDate);
		attributeGetterFunctions.put("status", supportR::getStatus);
		attributeSetterBiConsumers.put(
			"status", (BiConsumer<supportR, String>)supportR::setStatus);
		attributeGetterFunctions.put("link", supportR::getLink);
		attributeSetterBiConsumers.put(
			"link", (BiConsumer<supportR, String>)supportR::setLink);
		attributeGetterFunctions.put("displayLink", supportR::getDisplayLink);
		attributeSetterBiConsumers.put(
			"displayLink",
			(BiConsumer<supportR, String>)supportR::setDisplayLink);
		attributeGetterFunctions.put(
			"calendarBookingId", supportR::getCalendarBookingId);
		attributeSetterBiConsumers.put(
			"calendarBookingId",
			(BiConsumer<supportR, Long>)supportR::setCalendarBookingId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getSupportRId() {
		return _supportRId;
	}

	@Override
	public void setSupportRId(long supportRId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_supportRId = supportRId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public Date getOriginalCreateDate() {
		return getColumnOriginalValue("createDate");
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getSpecificParty() {
		if (_specificParty == null) {
			return "";
		}
		else {
			return _specificParty;
		}
	}

	@Override
	public void setSpecificParty(String specificParty) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_specificParty = specificParty;
	}

	@JSON
	@Override
	public long getOrgSiteId() {
		return _orgSiteId;
	}

	@Override
	public void setOrgSiteId(long orgSiteId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_orgSiteId = orgSiteId;
	}

	@JSON
	@Override
	public String getType() {
		if (_type == null) {
			return "";
		}
		else {
			return _type;
		}
	}

	@Override
	public void setType(String type) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_type = type;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalType() {
		return getColumnOriginalValue("type_");
	}

	@JSON
	@Override
	public String getTitle() {
		if (_title == null) {
			return "";
		}
		else {
			return _title;
		}
	}

	@Override
	public void setTitle(String title) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_title = title;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalTitle() {
		return getColumnOriginalValue("title");
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_description = description;
	}

	@JSON
	@Override
	public Date getDueDate() {
		return _dueDate;
	}

	@Override
	public void setDueDate(Date dueDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dueDate = dueDate;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public Date getOriginalDueDate() {
		return getColumnOriginalValue("dueDate");
	}

	@JSON
	@Override
	public String getStatus() {
		if (_status == null) {
			return "";
		}
		else {
			return _status;
		}
	}

	@Override
	public void setStatus(String status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalStatus() {
		return getColumnOriginalValue("status");
	}

	@JSON
	@Override
	public String getLink() {
		if (_link == null) {
			return "";
		}
		else {
			return _link;
		}
	}

	@Override
	public void setLink(String link) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_link = link;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalLink() {
		return getColumnOriginalValue("link");
	}

	@JSON
	@Override
	public String getDisplayLink() {
		if (_displayLink == null) {
			return "";
		}
		else {
			return _displayLink;
		}
	}

	@Override
	public void setDisplayLink(String displayLink) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_displayLink = displayLink;
	}

	@JSON
	@Override
	public long getCalendarBookingId() {
		return _calendarBookingId;
	}

	@Override
	public void setCalendarBookingId(long calendarBookingId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_calendarBookingId = calendarBookingId;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(supportR.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (entry.getValue() != getColumnValue(entry.getKey())) {
				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), supportR.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public supportR toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, supportR>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		supportRImpl supportRImpl = new supportRImpl();

		supportRImpl.setUuid(getUuid());
		supportRImpl.setSupportRId(getSupportRId());
		supportRImpl.setGroupId(getGroupId());
		supportRImpl.setCompanyId(getCompanyId());
		supportRImpl.setUserId(getUserId());
		supportRImpl.setUserName(getUserName());
		supportRImpl.setCreateDate(getCreateDate());
		supportRImpl.setModifiedDate(getModifiedDate());
		supportRImpl.setSpecificParty(getSpecificParty());
		supportRImpl.setOrgSiteId(getOrgSiteId());
		supportRImpl.setType(getType());
		supportRImpl.setTitle(getTitle());
		supportRImpl.setDescription(getDescription());
		supportRImpl.setDueDate(getDueDate());
		supportRImpl.setStatus(getStatus());
		supportRImpl.setLink(getLink());
		supportRImpl.setDisplayLink(getDisplayLink());
		supportRImpl.setCalendarBookingId(getCalendarBookingId());

		supportRImpl.resetOriginalValues();

		return supportRImpl;
	}

	@Override
	public int compareTo(supportR supportR) {
		int value = 0;

		value = DateUtil.compareTo(getCreateDate(), supportR.getCreateDate());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof supportR)) {
			return false;
		}

		supportR supportR = (supportR)object;

		long primaryKey = supportR.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<supportR> toCacheModel() {
		supportRCacheModel supportRCacheModel = new supportRCacheModel();

		supportRCacheModel.uuid = getUuid();

		String uuid = supportRCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			supportRCacheModel.uuid = null;
		}

		supportRCacheModel.supportRId = getSupportRId();

		supportRCacheModel.groupId = getGroupId();

		supportRCacheModel.companyId = getCompanyId();

		supportRCacheModel.userId = getUserId();

		supportRCacheModel.userName = getUserName();

		String userName = supportRCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			supportRCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			supportRCacheModel.createDate = createDate.getTime();
		}
		else {
			supportRCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			supportRCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			supportRCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		supportRCacheModel.specificParty = getSpecificParty();

		String specificParty = supportRCacheModel.specificParty;

		if ((specificParty != null) && (specificParty.length() == 0)) {
			supportRCacheModel.specificParty = null;
		}

		supportRCacheModel.orgSiteId = getOrgSiteId();

		supportRCacheModel.type = getType();

		String type = supportRCacheModel.type;

		if ((type != null) && (type.length() == 0)) {
			supportRCacheModel.type = null;
		}

		supportRCacheModel.title = getTitle();

		String title = supportRCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			supportRCacheModel.title = null;
		}

		supportRCacheModel.description = getDescription();

		String description = supportRCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			supportRCacheModel.description = null;
		}

		Date dueDate = getDueDate();

		if (dueDate != null) {
			supportRCacheModel.dueDate = dueDate.getTime();
		}
		else {
			supportRCacheModel.dueDate = Long.MIN_VALUE;
		}

		supportRCacheModel.status = getStatus();

		String status = supportRCacheModel.status;

		if ((status != null) && (status.length() == 0)) {
			supportRCacheModel.status = null;
		}

		supportRCacheModel.link = getLink();

		String link = supportRCacheModel.link;

		if ((link != null) && (link.length() == 0)) {
			supportRCacheModel.link = null;
		}

		supportRCacheModel.displayLink = getDisplayLink();

		String displayLink = supportRCacheModel.displayLink;

		if ((displayLink != null) && (displayLink.length() == 0)) {
			supportRCacheModel.displayLink = null;
		}

		supportRCacheModel.calendarBookingId = getCalendarBookingId();

		return supportRCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<supportR, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<supportR, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<supportR, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((supportR)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<supportR, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<supportR, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<supportR, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((supportR)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, supportR>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private long _supportRId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _specificParty;
	private long _orgSiteId;
	private String _type;
	private String _title;
	private String _description;
	private Date _dueDate;
	private String _status;
	private String _link;
	private String _displayLink;
	private long _calendarBookingId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<supportR, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((supportR)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("supportRId", _supportRId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("specificParty", _specificParty);
		_columnOriginalValues.put("orgSiteId", _orgSiteId);
		_columnOriginalValues.put("type_", _type);
		_columnOriginalValues.put("title", _title);
		_columnOriginalValues.put("description", _description);
		_columnOriginalValues.put("dueDate", _dueDate);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("link", _link);
		_columnOriginalValues.put("displayLink", _displayLink);
		_columnOriginalValues.put("calendarBookingId", _calendarBookingId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put("type_", "type");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("supportRId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("specificParty", 256L);

		columnBitmasks.put("orgSiteId", 512L);

		columnBitmasks.put("type_", 1024L);

		columnBitmasks.put("title", 2048L);

		columnBitmasks.put("description", 4096L);

		columnBitmasks.put("dueDate", 8192L);

		columnBitmasks.put("status", 16384L);

		columnBitmasks.put("link", 32768L);

		columnBitmasks.put("displayLink", 65536L);

		columnBitmasks.put("calendarBookingId", 131072L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private supportR _escapedModel;

}