/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package rec.link.menu.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the LinkMenu service. Represents a row in the &quot;LinkMenu_LinkMenu&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>rec.link.menu.model.impl.LinkMenuModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>rec.link.menu.model.impl.LinkMenuImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LinkMenu
 * @generated
 */
@ProviderType
public interface LinkMenuModel
	extends BaseModel<LinkMenu>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a link menu model instance should use the {@link LinkMenu} interface instead.
	 */

	/**
	 * Returns the primary key of this link menu.
	 *
	 * @return the primary key of this link menu
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this link menu.
	 *
	 * @param primaryKey the primary key of this link menu
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this link menu.
	 *
	 * @return the uuid of this link menu
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this link menu.
	 *
	 * @param uuid the uuid of this link menu
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the link ID of this link menu.
	 *
	 * @return the link ID of this link menu
	 */
	public long getLinkId();

	/**
	 * Sets the link ID of this link menu.
	 *
	 * @param linkId the link ID of this link menu
	 */
	public void setLinkId(long linkId);

	/**
	 * Returns the group ID of this link menu.
	 *
	 * @return the group ID of this link menu
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this link menu.
	 *
	 * @param groupId the group ID of this link menu
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this link menu.
	 *
	 * @return the company ID of this link menu
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this link menu.
	 *
	 * @param companyId the company ID of this link menu
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this link menu.
	 *
	 * @return the user ID of this link menu
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this link menu.
	 *
	 * @param userId the user ID of this link menu
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this link menu.
	 *
	 * @return the user uuid of this link menu
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this link menu.
	 *
	 * @param userUuid the user uuid of this link menu
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this link menu.
	 *
	 * @return the user name of this link menu
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this link menu.
	 *
	 * @param userName the user name of this link menu
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this link menu.
	 *
	 * @return the create date of this link menu
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this link menu.
	 *
	 * @param createDate the create date of this link menu
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this link menu.
	 *
	 * @return the modified date of this link menu
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this link menu.
	 *
	 * @param modifiedDate the modified date of this link menu
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the link name of this link menu.
	 *
	 * @return the link name of this link menu
	 */
	@AutoEscape
	public String getLinkName();

	/**
	 * Sets the link name of this link menu.
	 *
	 * @param linkName the link name of this link menu
	 */
	public void setLinkName(String linkName);

	/**
	 * Returns the link of this link menu.
	 *
	 * @return the link of this link menu
	 */
	@AutoEscape
	public String getLink();

	/**
	 * Sets the link of this link menu.
	 *
	 * @param link the link of this link menu
	 */
	public void setLink(String link);

	/**
	 * Returns the link position of this link menu.
	 *
	 * @return the link position of this link menu
	 */
	public int getLinkPosition();

	/**
	 * Sets the link position of this link menu.
	 *
	 * @param linkPosition the link position of this link menu
	 */
	public void setLinkPosition(int linkPosition);

	/**
	 * Returns the icon name of this link menu.
	 *
	 * @return the icon name of this link menu
	 */
	@AutoEscape
	public String getIconName();

	/**
	 * Sets the icon name of this link menu.
	 *
	 * @param iconName the icon name of this link menu
	 */
	public void setIconName(String iconName);

}