/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package rec.customnotification.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import rec.customnotification.model.NotificationRpa;
import rec.customnotification.model.NotificationRpaModel;
import rec.customnotification.model.NotificationRpaSoap;

/**
 * The base model implementation for the NotificationRpa service. Represents a row in the &quot;REC_NotificationRpa&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>NotificationRpaModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link NotificationRpaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see NotificationRpaImpl
 * @generated
 */
@JSON(strict = true)
public class NotificationRpaModelImpl
	extends BaseModelImpl<NotificationRpa> implements NotificationRpaModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a notification rpa model instance should use the <code>NotificationRpa</code> interface instead.
	 */
	public static final String TABLE_NAME = "REC_NotificationRpa";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"customNotificationId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"plidPage", Types.BIGINT}, {"targetName", Types.VARCHAR},
		{"notificationTitle", Types.VARCHAR},
		{"notificationBody", Types.VARCHAR}, {"url", Types.VARCHAR},
		{"deliveryMethod", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("customNotificationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("plidPage", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("targetName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("notificationTitle", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("notificationBody", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("url", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("deliveryMethod", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table REC_NotificationRpa (uuid_ VARCHAR(75) null,customNotificationId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,plidPage LONG,targetName VARCHAR(75) null,notificationTitle VARCHAR(250) null,notificationBody VARCHAR(500) null,url VARCHAR(75) null,deliveryMethod VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table REC_NotificationRpa";

	public static final String ORDER_BY_JPQL =
		" ORDER BY notificationRpa.createDate ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY REC_NotificationRpa.createDate ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long CREATEDATE_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long NOTIFICATIONBODY_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long NOTIFICATIONTITLE_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long PLIDPAGE_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long TARGETNAME_COLUMN_BITMASK = 64L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 128L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static NotificationRpa toModel(NotificationRpaSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		NotificationRpa model = new NotificationRpaImpl();

		model.setUuid(soapModel.getUuid());
		model.setCustomNotificationId(soapModel.getCustomNotificationId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setPlidPage(soapModel.getPlidPage());
		model.setTargetName(soapModel.getTargetName());
		model.setNotificationTitle(soapModel.getNotificationTitle());
		model.setNotificationBody(soapModel.getNotificationBody());
		model.setUrl(soapModel.getUrl());
		model.setDeliveryMethod(soapModel.getDeliveryMethod());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<NotificationRpa> toModels(
		NotificationRpaSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<NotificationRpa> models = new ArrayList<NotificationRpa>(
			soapModels.length);

		for (NotificationRpaSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public NotificationRpaModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _customNotificationId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCustomNotificationId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _customNotificationId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return NotificationRpa.class;
	}

	@Override
	public String getModelClassName() {
		return NotificationRpa.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<NotificationRpa, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<NotificationRpa, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<NotificationRpa, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((NotificationRpa)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<NotificationRpa, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<NotificationRpa, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(NotificationRpa)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<NotificationRpa, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<NotificationRpa, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, NotificationRpa>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			NotificationRpa.class.getClassLoader(), NotificationRpa.class,
			ModelWrapper.class);

		try {
			Constructor<NotificationRpa> constructor =
				(Constructor<NotificationRpa>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<NotificationRpa, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<NotificationRpa, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<NotificationRpa, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<NotificationRpa, Object>>();
		Map<String, BiConsumer<NotificationRpa, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<NotificationRpa, ?>>();

		attributeGetterFunctions.put("uuid", NotificationRpa::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<NotificationRpa, String>)NotificationRpa::setUuid);
		attributeGetterFunctions.put(
			"customNotificationId", NotificationRpa::getCustomNotificationId);
		attributeSetterBiConsumers.put(
			"customNotificationId",
			(BiConsumer<NotificationRpa, Long>)
				NotificationRpa::setCustomNotificationId);
		attributeGetterFunctions.put("groupId", NotificationRpa::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<NotificationRpa, Long>)NotificationRpa::setGroupId);
		attributeGetterFunctions.put(
			"companyId", NotificationRpa::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<NotificationRpa, Long>)NotificationRpa::setCompanyId);
		attributeGetterFunctions.put("userId", NotificationRpa::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<NotificationRpa, Long>)NotificationRpa::setUserId);
		attributeGetterFunctions.put("userName", NotificationRpa::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<NotificationRpa, String>)NotificationRpa::setUserName);
		attributeGetterFunctions.put(
			"createDate", NotificationRpa::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<NotificationRpa, Date>)NotificationRpa::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", NotificationRpa::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<NotificationRpa, Date>)
				NotificationRpa::setModifiedDate);
		attributeGetterFunctions.put("plidPage", NotificationRpa::getPlidPage);
		attributeSetterBiConsumers.put(
			"plidPage",
			(BiConsumer<NotificationRpa, Long>)NotificationRpa::setPlidPage);
		attributeGetterFunctions.put(
			"targetName", NotificationRpa::getTargetName);
		attributeSetterBiConsumers.put(
			"targetName",
			(BiConsumer<NotificationRpa, String>)
				NotificationRpa::setTargetName);
		attributeGetterFunctions.put(
			"notificationTitle", NotificationRpa::getNotificationTitle);
		attributeSetterBiConsumers.put(
			"notificationTitle",
			(BiConsumer<NotificationRpa, String>)
				NotificationRpa::setNotificationTitle);
		attributeGetterFunctions.put(
			"notificationBody", NotificationRpa::getNotificationBody);
		attributeSetterBiConsumers.put(
			"notificationBody",
			(BiConsumer<NotificationRpa, String>)
				NotificationRpa::setNotificationBody);
		attributeGetterFunctions.put("url", NotificationRpa::getUrl);
		attributeSetterBiConsumers.put(
			"url",
			(BiConsumer<NotificationRpa, String>)NotificationRpa::setUrl);
		attributeGetterFunctions.put(
			"deliveryMethod", NotificationRpa::getDeliveryMethod);
		attributeSetterBiConsumers.put(
			"deliveryMethod",
			(BiConsumer<NotificationRpa, String>)
				NotificationRpa::setDeliveryMethod);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getCustomNotificationId() {
		return _customNotificationId;
	}

	@Override
	public void setCustomNotificationId(long customNotificationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_customNotificationId = customNotificationId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public Date getOriginalCreateDate() {
		return getColumnOriginalValue("createDate");
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getPlidPage() {
		return _plidPage;
	}

	@Override
	public void setPlidPage(long plidPage) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_plidPage = plidPage;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalPlidPage() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("plidPage"));
	}

	@JSON
	@Override
	public String getTargetName() {
		if (_targetName == null) {
			return "";
		}
		else {
			return _targetName;
		}
	}

	@Override
	public void setTargetName(String targetName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_targetName = targetName;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalTargetName() {
		return getColumnOriginalValue("targetName");
	}

	@JSON
	@Override
	public String getNotificationTitle() {
		if (_notificationTitle == null) {
			return "";
		}
		else {
			return _notificationTitle;
		}
	}

	@Override
	public void setNotificationTitle(String notificationTitle) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_notificationTitle = notificationTitle;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalNotificationTitle() {
		return getColumnOriginalValue("notificationTitle");
	}

	@JSON
	@Override
	public String getNotificationBody() {
		if (_notificationBody == null) {
			return "";
		}
		else {
			return _notificationBody;
		}
	}

	@Override
	public void setNotificationBody(String notificationBody) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_notificationBody = notificationBody;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalNotificationBody() {
		return getColumnOriginalValue("notificationBody");
	}

	@JSON
	@Override
	public String getUrl() {
		if (_url == null) {
			return "";
		}
		else {
			return _url;
		}
	}

	@Override
	public void setUrl(String url) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_url = url;
	}

	@JSON
	@Override
	public String getDeliveryMethod() {
		if (_deliveryMethod == null) {
			return "";
		}
		else {
			return _deliveryMethod;
		}
	}

	@Override
	public void setDeliveryMethod(String deliveryMethod) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_deliveryMethod = deliveryMethod;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(NotificationRpa.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (entry.getValue() != getColumnValue(entry.getKey())) {
				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), NotificationRpa.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public NotificationRpa toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, NotificationRpa>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		NotificationRpaImpl notificationRpaImpl = new NotificationRpaImpl();

		notificationRpaImpl.setUuid(getUuid());
		notificationRpaImpl.setCustomNotificationId(getCustomNotificationId());
		notificationRpaImpl.setGroupId(getGroupId());
		notificationRpaImpl.setCompanyId(getCompanyId());
		notificationRpaImpl.setUserId(getUserId());
		notificationRpaImpl.setUserName(getUserName());
		notificationRpaImpl.setCreateDate(getCreateDate());
		notificationRpaImpl.setModifiedDate(getModifiedDate());
		notificationRpaImpl.setPlidPage(getPlidPage());
		notificationRpaImpl.setTargetName(getTargetName());
		notificationRpaImpl.setNotificationTitle(getNotificationTitle());
		notificationRpaImpl.setNotificationBody(getNotificationBody());
		notificationRpaImpl.setUrl(getUrl());
		notificationRpaImpl.setDeliveryMethod(getDeliveryMethod());

		notificationRpaImpl.resetOriginalValues();

		return notificationRpaImpl;
	}

	@Override
	public int compareTo(NotificationRpa notificationRpa) {
		int value = 0;

		value = DateUtil.compareTo(
			getCreateDate(), notificationRpa.getCreateDate());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof NotificationRpa)) {
			return false;
		}

		NotificationRpa notificationRpa = (NotificationRpa)object;

		long primaryKey = notificationRpa.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<NotificationRpa> toCacheModel() {
		NotificationRpaCacheModel notificationRpaCacheModel =
			new NotificationRpaCacheModel();

		notificationRpaCacheModel.uuid = getUuid();

		String uuid = notificationRpaCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			notificationRpaCacheModel.uuid = null;
		}

		notificationRpaCacheModel.customNotificationId =
			getCustomNotificationId();

		notificationRpaCacheModel.groupId = getGroupId();

		notificationRpaCacheModel.companyId = getCompanyId();

		notificationRpaCacheModel.userId = getUserId();

		notificationRpaCacheModel.userName = getUserName();

		String userName = notificationRpaCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			notificationRpaCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			notificationRpaCacheModel.createDate = createDate.getTime();
		}
		else {
			notificationRpaCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			notificationRpaCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			notificationRpaCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		notificationRpaCacheModel.plidPage = getPlidPage();

		notificationRpaCacheModel.targetName = getTargetName();

		String targetName = notificationRpaCacheModel.targetName;

		if ((targetName != null) && (targetName.length() == 0)) {
			notificationRpaCacheModel.targetName = null;
		}

		notificationRpaCacheModel.notificationTitle = getNotificationTitle();

		String notificationTitle = notificationRpaCacheModel.notificationTitle;

		if ((notificationTitle != null) && (notificationTitle.length() == 0)) {
			notificationRpaCacheModel.notificationTitle = null;
		}

		notificationRpaCacheModel.notificationBody = getNotificationBody();

		String notificationBody = notificationRpaCacheModel.notificationBody;

		if ((notificationBody != null) && (notificationBody.length() == 0)) {
			notificationRpaCacheModel.notificationBody = null;
		}

		notificationRpaCacheModel.url = getUrl();

		String url = notificationRpaCacheModel.url;

		if ((url != null) && (url.length() == 0)) {
			notificationRpaCacheModel.url = null;
		}

		notificationRpaCacheModel.deliveryMethod = getDeliveryMethod();

		String deliveryMethod = notificationRpaCacheModel.deliveryMethod;

		if ((deliveryMethod != null) && (deliveryMethod.length() == 0)) {
			notificationRpaCacheModel.deliveryMethod = null;
		}

		return notificationRpaCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<NotificationRpa, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<NotificationRpa, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<NotificationRpa, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((NotificationRpa)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<NotificationRpa, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<NotificationRpa, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<NotificationRpa, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((NotificationRpa)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, NotificationRpa>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private long _customNotificationId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _plidPage;
	private String _targetName;
	private String _notificationTitle;
	private String _notificationBody;
	private String _url;
	private String _deliveryMethod;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<NotificationRpa, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((NotificationRpa)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put(
			"customNotificationId", _customNotificationId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("plidPage", _plidPage);
		_columnOriginalValues.put("targetName", _targetName);
		_columnOriginalValues.put("notificationTitle", _notificationTitle);
		_columnOriginalValues.put("notificationBody", _notificationBody);
		_columnOriginalValues.put("url", _url);
		_columnOriginalValues.put("deliveryMethod", _deliveryMethod);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("customNotificationId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("plidPage", 256L);

		columnBitmasks.put("targetName", 512L);

		columnBitmasks.put("notificationTitle", 1024L);

		columnBitmasks.put("notificationBody", 2048L);

		columnBitmasks.put("url", 4096L);

		columnBitmasks.put("deliveryMethod", 8192L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private NotificationRpa _escapedModel;

}