/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.everis.rec.maintenanceactivity.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the MaintenanceActivity service. Represents a row in the &quot;AMA_MaintenanceActivity&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.everis.rec.maintenanceactivity.model.impl.MaintenanceActivityModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.everis.rec.maintenanceactivity.model.impl.MaintenanceActivityImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MaintenanceActivity
 * @generated
 */
@ProviderType
public interface MaintenanceActivityModel
	extends BaseModel<MaintenanceActivity>, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a maintenance activity model instance should use the {@link MaintenanceActivity} interface instead.
	 */

	/**
	 * Returns the primary key of this maintenance activity.
	 *
	 * @return the primary key of this maintenance activity
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this maintenance activity.
	 *
	 * @param primaryKey the primary key of this maintenance activity
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this maintenance activity.
	 *
	 * @return the uuid of this maintenance activity
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this maintenance activity.
	 *
	 * @param uuid the uuid of this maintenance activity
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the maintenanceactivity ID of this maintenance activity.
	 *
	 * @return the maintenanceactivity ID of this maintenance activity
	 */
	public long getMaintenanceactivityId();

	/**
	 * Sets the maintenanceactivity ID of this maintenance activity.
	 *
	 * @param maintenanceactivityId the maintenanceactivity ID of this maintenance activity
	 */
	public void setMaintenanceactivityId(long maintenanceactivityId);

	/**
	 * Returns the company ID of this maintenance activity.
	 *
	 * @return the company ID of this maintenance activity
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this maintenance activity.
	 *
	 * @param companyId the company ID of this maintenance activity
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this maintenance activity.
	 *
	 * @return the user ID of this maintenance activity
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this maintenance activity.
	 *
	 * @param userId the user ID of this maintenance activity
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this maintenance activity.
	 *
	 * @return the user uuid of this maintenance activity
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this maintenance activity.
	 *
	 * @param userUuid the user uuid of this maintenance activity
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this maintenance activity.
	 *
	 * @return the user name of this maintenance activity
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this maintenance activity.
	 *
	 * @param userName the user name of this maintenance activity
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this maintenance activity.
	 *
	 * @return the create date of this maintenance activity
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this maintenance activity.
	 *
	 * @param createDate the create date of this maintenance activity
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this maintenance activity.
	 *
	 * @return the modified date of this maintenance activity
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this maintenance activity.
	 *
	 * @param modifiedDate the modified date of this maintenance activity
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the activity title of this maintenance activity.
	 *
	 * @return the activity title of this maintenance activity
	 */
	@AutoEscape
	public String getActivityTitle();

	/**
	 * Sets the activity title of this maintenance activity.
	 *
	 * @param activityTitle the activity title of this maintenance activity
	 */
	public void setActivityTitle(String activityTitle);

	/**
	 * Returns the due date of this maintenance activity.
	 *
	 * @return the due date of this maintenance activity
	 */
	@AutoEscape
	public String getDueDate();

	/**
	 * Sets the due date of this maintenance activity.
	 *
	 * @param dueDate the due date of this maintenance activity
	 */
	public void setDueDate(String dueDate);

	/**
	 * Returns the status of this maintenance activity.
	 *
	 * @return the status of this maintenance activity
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this maintenance activity.
	 *
	 * @param status the status of this maintenance activity
	 */
	public void setStatus(String status);

	/**
	 * Returns the org site ID of this maintenance activity.
	 *
	 * @return the org site ID of this maintenance activity
	 */
	public long getOrgSiteId();

	/**
	 * Sets the org site ID of this maintenance activity.
	 *
	 * @param orgSiteId the org site ID of this maintenance activity
	 */
	public void setOrgSiteId(long orgSiteId);

	/**
	 * Returns the specific party of this maintenance activity.
	 *
	 * @return the specific party of this maintenance activity
	 */
	@AutoEscape
	public String getSpecificParty();

	/**
	 * Sets the specific party of this maintenance activity.
	 *
	 * @param specificParty the specific party of this maintenance activity
	 */
	public void setSpecificParty(String specificParty);

	/**
	 * Returns the due date formated of this maintenance activity.
	 *
	 * @return the due date formated of this maintenance activity
	 */
	public Date getDueDateFormated();

	/**
	 * Sets the due date formated of this maintenance activity.
	 *
	 * @param dueDateFormated the due date formated of this maintenance activity
	 */
	public void setDueDateFormated(Date dueDateFormated);

	/**
	 * Returns the calendar booking ID of this maintenance activity.
	 *
	 * @return the calendar booking ID of this maintenance activity
	 */
	public long getCalendarBookingId();

	/**
	 * Sets the calendar booking ID of this maintenance activity.
	 *
	 * @param calendarBookingId the calendar booking ID of this maintenance activity
	 */
	public void setCalendarBookingId(long calendarBookingId);

}