/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package rec.confidential.message.model.impl;

import rec.confidential.message.model.Confidential_Messages;
import rec.confidential.message.service.Confidential_MessagesLocalServiceUtil;

/**
 * The extended model base implementation for the Confidential_Messages service. Represents a row in the &quot;confidential_messages&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Confidential_MessagesImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Confidential_MessagesImpl
 * @see Confidential_Messages
 * @generated
 */
public abstract class Confidential_MessagesBaseImpl
	extends Confidential_MessagesModelImpl implements Confidential_Messages {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a confidential_ messages model instance should use the <code>Confidential_Messages</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			Confidential_MessagesLocalServiceUtil.addConfidential_Messages(
				this);
		}
		else {
			Confidential_MessagesLocalServiceUtil.updateConfidential_Messages(
				this);
		}
	}

}