/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.everis.rec.rfilogs.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the RfiLogs service. Represents a row in the &quot;RFI_RfiLogs&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.everis.rec.rfilogs.model.impl.RfiLogsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.everis.rec.rfilogs.model.impl.RfiLogsImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RfiLogs
 * @generated
 */
@ProviderType
public interface RfiLogsModel
	extends BaseModel<RfiLogs>, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a rfi logs model instance should use the {@link RfiLogs} interface instead.
	 */

	/**
	 * Returns the primary key of this rfi logs.
	 *
	 * @return the primary key of this rfi logs
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this rfi logs.
	 *
	 * @param primaryKey the primary key of this rfi logs
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this rfi logs.
	 *
	 * @return the uuid of this rfi logs
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this rfi logs.
	 *
	 * @param uuid the uuid of this rfi logs
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the rfilog ID of this rfi logs.
	 *
	 * @return the rfilog ID of this rfi logs
	 */
	public long getRfilogId();

	/**
	 * Sets the rfilog ID of this rfi logs.
	 *
	 * @param rfilogId the rfilog ID of this rfi logs
	 */
	public void setRfilogId(long rfilogId);

	/**
	 * Returns the company ID of this rfi logs.
	 *
	 * @return the company ID of this rfi logs
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this rfi logs.
	 *
	 * @param companyId the company ID of this rfi logs
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this rfi logs.
	 *
	 * @return the user ID of this rfi logs
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this rfi logs.
	 *
	 * @param userId the user ID of this rfi logs
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this rfi logs.
	 *
	 * @return the user uuid of this rfi logs
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this rfi logs.
	 *
	 * @param userUuid the user uuid of this rfi logs
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this rfi logs.
	 *
	 * @return the user name of this rfi logs
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this rfi logs.
	 *
	 * @param userName the user name of this rfi logs
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this rfi logs.
	 *
	 * @return the create date of this rfi logs
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this rfi logs.
	 *
	 * @param createDate the create date of this rfi logs
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this rfi logs.
	 *
	 * @return the modified date of this rfi logs
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this rfi logs.
	 *
	 * @param modifiedDate the modified date of this rfi logs
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the req ID of this rfi logs.
	 *
	 * @return the req ID of this rfi logs
	 */
	public long getReqId();

	/**
	 * Sets the req ID of this rfi logs.
	 *
	 * @param reqId the req ID of this rfi logs
	 */
	public void setReqId(long reqId);

	/**
	 * Returns the specific party of this rfi logs.
	 *
	 * @return the specific party of this rfi logs
	 */
	@AutoEscape
	public String getSpecificParty();

	/**
	 * Sets the specific party of this rfi logs.
	 *
	 * @param specificParty the specific party of this rfi logs
	 */
	public void setSpecificParty(String specificParty);

	/**
	 * Returns the org site ID of this rfi logs.
	 *
	 * @return the org site ID of this rfi logs
	 */
	public long getOrgSiteId();

	/**
	 * Sets the org site ID of this rfi logs.
	 *
	 * @param orgSiteId the org site ID of this rfi logs
	 */
	public void setOrgSiteId(long orgSiteId);

	/**
	 * Returns the title of this rfi logs.
	 *
	 * @return the title of this rfi logs
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this rfi logs.
	 *
	 * @param title the title of this rfi logs
	 */
	public void setTitle(String title);

	/**
	 * Returns the due date of this rfi logs.
	 *
	 * @return the due date of this rfi logs
	 */
	@AutoEscape
	public String getDueDate();

	/**
	 * Sets the due date of this rfi logs.
	 *
	 * @param dueDate the due date of this rfi logs
	 */
	public void setDueDate(String dueDate);

	/**
	 * Returns the status of this rfi logs.
	 *
	 * @return the status of this rfi logs
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this rfi logs.
	 *
	 * @param status the status of this rfi logs
	 */
	public void setStatus(String status);

	/**
	 * Returns the req desc of this rfi logs.
	 *
	 * @return the req desc of this rfi logs
	 */
	@AutoEscape
	public String getReqDesc();

	/**
	 * Sets the req desc of this rfi logs.
	 *
	 * @param reqDesc the req desc of this rfi logs
	 */
	public void setReqDesc(String reqDesc);

	/**
	 * Returns the rationale of this rfi logs.
	 *
	 * @return the rationale of this rfi logs
	 */
	@AutoEscape
	public String getRationale();

	/**
	 * Sets the rationale of this rfi logs.
	 *
	 * @param rationale the rationale of this rfi logs
	 */
	public void setRationale(String rationale);

	/**
	 * Returns the due date formated of this rfi logs.
	 *
	 * @return the due date formated of this rfi logs
	 */
	public Date getDueDateFormated();

	/**
	 * Sets the due date formated of this rfi logs.
	 *
	 * @param dueDateFormated the due date formated of this rfi logs
	 */
	public void setDueDateFormated(Date dueDateFormated);

	/**
	 * Returns the calendar booking ID of this rfi logs.
	 *
	 * @return the calendar booking ID of this rfi logs
	 */
	public long getCalendarBookingId();

	/**
	 * Sets the calendar booking ID of this rfi logs.
	 *
	 * @param calendarBookingId the calendar booking ID of this rfi logs
	 */
	public void setCalendarBookingId(long calendarBookingId);

}