/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.everis.rec.cpimpact.model.impl;

import com.everis.rec.cpimpact.model.CPImpact;
import com.everis.rec.cpimpact.model.CPImpactModel;
import com.everis.rec.cpimpact.model.CPImpactSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CPImpact service. Represents a row in the &quot;CPIMPACT_CPImpact&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>CPImpactModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CPImpactImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CPImpactImpl
 * @generated
 */
@JSON(strict = true)
public class CPImpactModelImpl
	extends BaseModelImpl<CPImpact> implements CPImpactModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a cp impact model instance should use the <code>CPImpact</code> interface instead.
	 */
	public static final String TABLE_NAME = "CPIMPACT_CPImpact";

	public static final Object[][] TABLE_COLUMNS = {
		{"impactId", Types.BIGINT}, {"impactName", Types.VARCHAR},
		{"impactCategory", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("impactId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("impactName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("impactCategory", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table CPIMPACT_CPImpact (impactId LONG not null primary key,impactName VARCHAR(75) null,impactCategory VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table CPIMPACT_CPImpact";

	public static final String ORDER_BY_JPQL =
		" ORDER BY cpImpact.impactId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY CPIMPACT_CPImpact.impactId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long IMPACTCATEGORY_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)
	 */
	@Deprecated
	public static final long IMPACTID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static CPImpact toModel(CPImpactSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		CPImpact model = new CPImpactImpl();

		model.setImpactId(soapModel.getImpactId());
		model.setImpactName(soapModel.getImpactName());
		model.setImpactCategory(soapModel.getImpactCategory());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<CPImpact> toModels(CPImpactSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<CPImpact> models = new ArrayList<CPImpact>(soapModels.length);

		for (CPImpactSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public CPImpactModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _impactId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setImpactId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _impactId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CPImpact.class;
	}

	@Override
	public String getModelClassName() {
		return CPImpact.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CPImpact, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CPImpact, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CPImpact, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((CPImpact)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CPImpact, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CPImpact, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CPImpact)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CPImpact, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CPImpact, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, CPImpact>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			CPImpact.class.getClassLoader(), CPImpact.class,
			ModelWrapper.class);

		try {
			Constructor<CPImpact> constructor =
				(Constructor<CPImpact>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<CPImpact, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<CPImpact, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<CPImpact, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<CPImpact, Object>>();
		Map<String, BiConsumer<CPImpact, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<CPImpact, ?>>();

		attributeGetterFunctions.put("impactId", CPImpact::getImpactId);
		attributeSetterBiConsumers.put(
			"impactId", (BiConsumer<CPImpact, Long>)CPImpact::setImpactId);
		attributeGetterFunctions.put("impactName", CPImpact::getImpactName);
		attributeSetterBiConsumers.put(
			"impactName",
			(BiConsumer<CPImpact, String>)CPImpact::setImpactName);
		attributeGetterFunctions.put(
			"impactCategory", CPImpact::getImpactCategory);
		attributeSetterBiConsumers.put(
			"impactCategory",
			(BiConsumer<CPImpact, String>)CPImpact::setImpactCategory);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getImpactId() {
		return _impactId;
	}

	@Override
	public void setImpactId(long impactId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_impactId = impactId;
	}

	@JSON
	@Override
	public String getImpactName() {
		if (_impactName == null) {
			return "";
		}
		else {
			return _impactName;
		}
	}

	@Override
	public void setImpactName(String impactName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_impactName = impactName;
	}

	@JSON
	@Override
	public String getImpactCategory() {
		if (_impactCategory == null) {
			return "";
		}
		else {
			return _impactCategory;
		}
	}

	@Override
	public void setImpactCategory(String impactCategory) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_impactCategory = impactCategory;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalImpactCategory() {
		return getColumnOriginalValue("impactCategory");
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (entry.getValue() != getColumnValue(entry.getKey())) {
				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, CPImpact.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CPImpact toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CPImpact>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CPImpactImpl cpImpactImpl = new CPImpactImpl();

		cpImpactImpl.setImpactId(getImpactId());
		cpImpactImpl.setImpactName(getImpactName());
		cpImpactImpl.setImpactCategory(getImpactCategory());

		cpImpactImpl.resetOriginalValues();

		return cpImpactImpl;
	}

	@Override
	public int compareTo(CPImpact cpImpact) {
		long primaryKey = cpImpact.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof CPImpact)) {
			return false;
		}

		CPImpact cpImpact = (CPImpact)object;

		long primaryKey = cpImpact.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<CPImpact> toCacheModel() {
		CPImpactCacheModel cpImpactCacheModel = new CPImpactCacheModel();

		cpImpactCacheModel.impactId = getImpactId();

		cpImpactCacheModel.impactName = getImpactName();

		String impactName = cpImpactCacheModel.impactName;

		if ((impactName != null) && (impactName.length() == 0)) {
			cpImpactCacheModel.impactName = null;
		}

		cpImpactCacheModel.impactCategory = getImpactCategory();

		String impactCategory = cpImpactCacheModel.impactCategory;

		if ((impactCategory != null) && (impactCategory.length() == 0)) {
			cpImpactCacheModel.impactCategory = null;
		}

		return cpImpactCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CPImpact, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CPImpact, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CPImpact, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((CPImpact)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<CPImpact, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<CPImpact, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CPImpact, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((CPImpact)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, CPImpact>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _impactId;
	private String _impactName;
	private String _impactCategory;

	public <T> T getColumnValue(String columnName) {
		Function<CPImpact, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((CPImpact)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("impactId", _impactId);
		_columnOriginalValues.put("impactName", _impactName);
		_columnOriginalValues.put("impactCategory", _impactCategory);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("impactId", 1L);

		columnBitmasks.put("impactName", 2L);

		columnBitmasks.put("impactCategory", 4L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private CPImpact _escapedModel;

}