/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.everis.rec.cpimpact.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CPImpact service. Represents a row in the &quot;CPIMPACT_CPImpact&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.everis.rec.cpimpact.model.impl.CPImpactModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.everis.rec.cpimpact.model.impl.CPImpactImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CPImpact
 * @generated
 */
@ProviderType
public interface CPImpactModel extends BaseModel<CPImpact> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cp impact model instance should use the {@link CPImpact} interface instead.
	 */

	/**
	 * Returns the primary key of this cp impact.
	 *
	 * @return the primary key of this cp impact
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this cp impact.
	 *
	 * @param primaryKey the primary key of this cp impact
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the impact ID of this cp impact.
	 *
	 * @return the impact ID of this cp impact
	 */
	public long getImpactId();

	/**
	 * Sets the impact ID of this cp impact.
	 *
	 * @param impactId the impact ID of this cp impact
	 */
	public void setImpactId(long impactId);

	/**
	 * Returns the impact name of this cp impact.
	 *
	 * @return the impact name of this cp impact
	 */
	@AutoEscape
	public String getImpactName();

	/**
	 * Sets the impact name of this cp impact.
	 *
	 * @param impactName the impact name of this cp impact
	 */
	public void setImpactName(String impactName);

	/**
	 * Returns the impact category of this cp impact.
	 *
	 * @return the impact category of this cp impact
	 */
	@AutoEscape
	public String getImpactCategory();

	/**
	 * Sets the impact category of this cp impact.
	 *
	 * @param impactCategory the impact category of this cp impact
	 */
	public void setImpactCategory(String impactCategory);

}