/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.everis.cproposal.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the recFormArticle service. Represents a row in the &quot;CPROPOSAL_recFormArticle&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.everis.cproposal.model.impl.recFormArticleModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.everis.cproposal.model.impl.recFormArticleImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see recFormArticle
 * @generated
 */
@ProviderType
public interface recFormArticleModel extends BaseModel<recFormArticle> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a rec form article model instance should use the {@link recFormArticle} interface instead.
	 */

	/**
	 * Returns the primary key of this rec form article.
	 *
	 * @return the primary key of this rec form article
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this rec form article.
	 *
	 * @param primaryKey the primary key of this rec form article
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the form ID of this rec form article.
	 *
	 * @return the form ID of this rec form article
	 */
	public long getFormId();

	/**
	 * Sets the form ID of this rec form article.
	 *
	 * @param formId the form ID of this rec form article
	 */
	public void setFormId(long formId);

	/**
	 * Returns the article ID of this rec form article.
	 *
	 * @return the article ID of this rec form article
	 */
	public long getArticleId();

	/**
	 * Sets the article ID of this rec form article.
	 *
	 * @param articleId the article ID of this rec form article
	 */
	public void setArticleId(long articleId);

	/**
	 * Returns the article status of this rec form article.
	 *
	 * @return the article status of this rec form article
	 */
	@AutoEscape
	public String getArticleStatus();

	/**
	 * Sets the article status of this rec form article.
	 *
	 * @param articleStatus the article status of this rec form article
	 */
	public void setArticleStatus(String articleStatus);

	/**
	 * Returns the article release schedule of this rec form article.
	 *
	 * @return the article release schedule of this rec form article
	 */
	@AutoEscape
	public String getArticleReleaseSchedule();

	/**
	 * Sets the article release schedule of this rec form article.
	 *
	 * @param articleReleaseSchedule the article release schedule of this rec form article
	 */
	public void setArticleReleaseSchedule(String articleReleaseSchedule);

	/**
	 * Returns the alternative form IDs of this rec form article.
	 *
	 * @return the alternative form IDs of this rec form article
	 */
	@AutoEscape
	public String getAlternativeFormIds();

	/**
	 * Sets the alternative form IDs of this rec form article.
	 *
	 * @param alternativeFormIds the alternative form IDs of this rec form article
	 */
	public void setAlternativeFormIds(String alternativeFormIds);

	/**
	 * Returns the article implementation date of this rec form article.
	 *
	 * @return the article implementation date of this rec form article
	 */
	public Date getArticleImplementationDate();

	/**
	 * Sets the article implementation date of this rec form article.
	 *
	 * @param articleImplementationDate the article implementation date of this rec form article
	 */
	public void setArticleImplementationDate(Date articleImplementationDate);

	/**
	 * Returns the article change path of this rec form article.
	 *
	 * @return the article change path of this rec form article
	 */
	@AutoEscape
	public String getArticleChangePath();

	/**
	 * Sets the article change path of this rec form article.
	 *
	 * @param articleChangePath the article change path of this rec form article
	 */
	public void setArticleChangePath(String articleChangePath);

	/**
	 * Returns the article responsible committee of this rec form article.
	 *
	 * @return the article responsible committee of this rec form article
	 */
	@AutoEscape
	public String getArticleResponsibleCommittee();

	/**
	 * Sets the article responsible committee of this rec form article.
	 *
	 * @param articleResponsibleCommittee the article responsible committee of this rec form article
	 */
	public void setArticleResponsibleCommittee(
		String articleResponsibleCommittee);

	/**
	 * Returns the article impacted parties of this rec form article.
	 *
	 * @return the article impacted parties of this rec form article
	 */
	@AutoEscape
	public String getArticleImpactedParties();

	/**
	 * Sets the article impacted parties of this rec form article.
	 *
	 * @param articleImpactedParties the article impacted parties of this rec form article
	 */
	public void setArticleImpactedParties(String articleImpactedParties);

	/**
	 * Returns the article change category of this rec form article.
	 *
	 * @return the article change category of this rec form article
	 */
	@AutoEscape
	public String getArticleChangeCategory();

	/**
	 * Sets the article change category of this rec form article.
	 *
	 * @param articleChangeCategory the article change category of this rec form article
	 */
	public void setArticleChangeCategory(String articleChangeCategory);

	/**
	 * Returns the article impacts of this rec form article.
	 *
	 * @return the article impacts of this rec form article
	 */
	@AutoEscape
	public String getArticleImpacts();

	/**
	 * Sets the article impacts of this rec form article.
	 *
	 * @param articleImpacts the article impacts of this rec form article
	 */
	public void setArticleImpacts(String articleImpacts);

}