/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package rec.customnotification.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the NotificationRpa service. Represents a row in the &quot;REC_NotificationRpa&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>rec.customnotification.model.impl.NotificationRpaModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>rec.customnotification.model.impl.NotificationRpaImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see NotificationRpa
 * @generated
 */
@ProviderType
public interface NotificationRpaModel
	extends BaseModel<NotificationRpa>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a notification rpa model instance should use the {@link NotificationRpa} interface instead.
	 */

	/**
	 * Returns the primary key of this notification rpa.
	 *
	 * @return the primary key of this notification rpa
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this notification rpa.
	 *
	 * @param primaryKey the primary key of this notification rpa
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this notification rpa.
	 *
	 * @return the uuid of this notification rpa
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this notification rpa.
	 *
	 * @param uuid the uuid of this notification rpa
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the custom notification ID of this notification rpa.
	 *
	 * @return the custom notification ID of this notification rpa
	 */
	public long getCustomNotificationId();

	/**
	 * Sets the custom notification ID of this notification rpa.
	 *
	 * @param customNotificationId the custom notification ID of this notification rpa
	 */
	public void setCustomNotificationId(long customNotificationId);

	/**
	 * Returns the group ID of this notification rpa.
	 *
	 * @return the group ID of this notification rpa
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this notification rpa.
	 *
	 * @param groupId the group ID of this notification rpa
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this notification rpa.
	 *
	 * @return the company ID of this notification rpa
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this notification rpa.
	 *
	 * @param companyId the company ID of this notification rpa
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this notification rpa.
	 *
	 * @return the user ID of this notification rpa
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this notification rpa.
	 *
	 * @param userId the user ID of this notification rpa
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this notification rpa.
	 *
	 * @return the user uuid of this notification rpa
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this notification rpa.
	 *
	 * @param userUuid the user uuid of this notification rpa
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this notification rpa.
	 *
	 * @return the user name of this notification rpa
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this notification rpa.
	 *
	 * @param userName the user name of this notification rpa
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this notification rpa.
	 *
	 * @return the create date of this notification rpa
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this notification rpa.
	 *
	 * @param createDate the create date of this notification rpa
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this notification rpa.
	 *
	 * @return the modified date of this notification rpa
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this notification rpa.
	 *
	 * @param modifiedDate the modified date of this notification rpa
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the plid page of this notification rpa.
	 *
	 * @return the plid page of this notification rpa
	 */
	public long getPlidPage();

	/**
	 * Sets the plid page of this notification rpa.
	 *
	 * @param plidPage the plid page of this notification rpa
	 */
	public void setPlidPage(long plidPage);

	/**
	 * Returns the target name of this notification rpa.
	 *
	 * @return the target name of this notification rpa
	 */
	@AutoEscape
	public String getTargetName();

	/**
	 * Sets the target name of this notification rpa.
	 *
	 * @param targetName the target name of this notification rpa
	 */
	public void setTargetName(String targetName);

	/**
	 * Returns the notification title of this notification rpa.
	 *
	 * @return the notification title of this notification rpa
	 */
	@AutoEscape
	public String getNotificationTitle();

	/**
	 * Sets the notification title of this notification rpa.
	 *
	 * @param notificationTitle the notification title of this notification rpa
	 */
	public void setNotificationTitle(String notificationTitle);

	/**
	 * Returns the notification body of this notification rpa.
	 *
	 * @return the notification body of this notification rpa
	 */
	@AutoEscape
	public String getNotificationBody();

	/**
	 * Sets the notification body of this notification rpa.
	 *
	 * @param notificationBody the notification body of this notification rpa
	 */
	public void setNotificationBody(String notificationBody);

	/**
	 * Returns the url of this notification rpa.
	 *
	 * @return the url of this notification rpa
	 */
	@AutoEscape
	public String getUrl();

	/**
	 * Sets the url of this notification rpa.
	 *
	 * @param url the url of this notification rpa
	 */
	public void setUrl(String url);

	/**
	 * Returns the delivery method of this notification rpa.
	 *
	 * @return the delivery method of this notification rpa
	 */
	@AutoEscape
	public String getDeliveryMethod();

	/**
	 * Sets the delivery method of this notification rpa.
	 *
	 * @param deliveryMethod the delivery method of this notification rpa
	 */
	public void setDeliveryMethod(String deliveryMethod);

}