/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.everis.rec.sites.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Recsites service. Represents a row in the &quot;RECSITES_Recsites&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.everis.rec.sites.model.impl.RecsitesModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.everis.rec.sites.model.impl.RecsitesImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Recsites
 * @generated
 */
@ProviderType
public interface RecsitesModel
	extends BaseModel<Recsites>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a recsites model instance should use the {@link Recsites} interface instead.
	 */

	/**
	 * Returns the primary key of this recsites.
	 *
	 * @return the primary key of this recsites
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this recsites.
	 *
	 * @param primaryKey the primary key of this recsites
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this recsites.
	 *
	 * @return the uuid of this recsites
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this recsites.
	 *
	 * @param uuid the uuid of this recsites
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the foo ID of this recsites.
	 *
	 * @return the foo ID of this recsites
	 */
	public long getFooId();

	/**
	 * Sets the foo ID of this recsites.
	 *
	 * @param fooId the foo ID of this recsites
	 */
	public void setFooId(long fooId);

	/**
	 * Returns the group ID of this recsites.
	 *
	 * @return the group ID of this recsites
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this recsites.
	 *
	 * @param groupId the group ID of this recsites
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this recsites.
	 *
	 * @return the company ID of this recsites
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this recsites.
	 *
	 * @param companyId the company ID of this recsites
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this recsites.
	 *
	 * @return the user ID of this recsites
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this recsites.
	 *
	 * @param userId the user ID of this recsites
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this recsites.
	 *
	 * @return the user uuid of this recsites
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this recsites.
	 *
	 * @param userUuid the user uuid of this recsites
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this recsites.
	 *
	 * @return the user name of this recsites
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this recsites.
	 *
	 * @param userName the user name of this recsites
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this recsites.
	 *
	 * @return the create date of this recsites
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this recsites.
	 *
	 * @param createDate the create date of this recsites
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this recsites.
	 *
	 * @return the modified date of this recsites
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this recsites.
	 *
	 * @param modifiedDate the modified date of this recsites
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the field1 of this recsites.
	 *
	 * @return the field1 of this recsites
	 */
	@AutoEscape
	public String getField1();

	/**
	 * Sets the field1 of this recsites.
	 *
	 * @param field1 the field1 of this recsites
	 */
	public void setField1(String field1);

	/**
	 * Returns the field2 of this recsites.
	 *
	 * @return the field2 of this recsites
	 */
	public boolean getField2();

	/**
	 * Returns <code>true</code> if this recsites is field2.
	 *
	 * @return <code>true</code> if this recsites is field2; <code>false</code> otherwise
	 */
	public boolean isField2();

	/**
	 * Sets whether this recsites is field2.
	 *
	 * @param field2 the field2 of this recsites
	 */
	public void setField2(boolean field2);

	/**
	 * Returns the field3 of this recsites.
	 *
	 * @return the field3 of this recsites
	 */
	public int getField3();

	/**
	 * Sets the field3 of this recsites.
	 *
	 * @param field3 the field3 of this recsites
	 */
	public void setField3(int field3);

	/**
	 * Returns the field4 of this recsites.
	 *
	 * @return the field4 of this recsites
	 */
	public Date getField4();

	/**
	 * Sets the field4 of this recsites.
	 *
	 * @param field4 the field4 of this recsites
	 */
	public void setField4(Date field4);

	/**
	 * Returns the field5 of this recsites.
	 *
	 * @return the field5 of this recsites
	 */
	@AutoEscape
	public String getField5();

	/**
	 * Sets the field5 of this recsites.
	 *
	 * @param field5 the field5 of this recsites
	 */
	public void setField5(String field5);

}