/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.everis.rec.maintenanceactivity.service.base;

import com.everis.rec.maintenanceactivity.model.MaintenanceActivity;
import com.everis.rec.maintenanceactivity.service.MaintenanceActivityLocalService;
import com.everis.rec.maintenanceactivity.service.persistence.MaintenanceActivityPersistence;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the maintenance activity local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.everis.rec.maintenanceactivity.service.impl.MaintenanceActivityLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.everis.rec.maintenanceactivity.service.impl.MaintenanceActivityLocalServiceImpl
 * @generated
 */
public abstract class MaintenanceActivityLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService,
			   MaintenanceActivityLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>MaintenanceActivityLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.everis.rec.maintenanceactivity.service.MaintenanceActivityLocalServiceUtil</code>.
	 */

	/**
	 * Adds the maintenance activity to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect MaintenanceActivityLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param maintenanceActivity the maintenance activity
	 * @return the maintenance activity that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public MaintenanceActivity addMaintenanceActivity(
		MaintenanceActivity maintenanceActivity) {

		maintenanceActivity.setNew(true);

		return maintenanceActivityPersistence.update(maintenanceActivity);
	}

	/**
	 * Creates a new maintenance activity with the primary key. Does not add the maintenance activity to the database.
	 *
	 * @param maintenanceactivityId the primary key for the new maintenance activity
	 * @return the new maintenance activity
	 */
	@Override
	@Transactional(enabled = false)
	public MaintenanceActivity createMaintenanceActivity(
		long maintenanceactivityId) {

		return maintenanceActivityPersistence.create(maintenanceactivityId);
	}

	/**
	 * Deletes the maintenance activity with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect MaintenanceActivityLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param maintenanceactivityId the primary key of the maintenance activity
	 * @return the maintenance activity that was removed
	 * @throws PortalException if a maintenance activity with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public MaintenanceActivity deleteMaintenanceActivity(
			long maintenanceactivityId)
		throws PortalException {

		return maintenanceActivityPersistence.remove(maintenanceactivityId);
	}

	/**
	 * Deletes the maintenance activity from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect MaintenanceActivityLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param maintenanceActivity the maintenance activity
	 * @return the maintenance activity that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public MaintenanceActivity deleteMaintenanceActivity(
		MaintenanceActivity maintenanceActivity) {

		return maintenanceActivityPersistence.remove(maintenanceActivity);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			MaintenanceActivity.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return maintenanceActivityPersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.everis.rec.maintenanceactivity.model.impl.MaintenanceActivityModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return maintenanceActivityPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.everis.rec.maintenanceactivity.model.impl.MaintenanceActivityModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return maintenanceActivityPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return maintenanceActivityPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return maintenanceActivityPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public MaintenanceActivity fetchMaintenanceActivity(
		long maintenanceactivityId) {

		return maintenanceActivityPersistence.fetchByPrimaryKey(
			maintenanceactivityId);
	}

	/**
	 * Returns the maintenance activity with the matching UUID and company.
	 *
	 * @param uuid the maintenance activity's UUID
	 * @param companyId the primary key of the company
	 * @return the matching maintenance activity, or <code>null</code> if a matching maintenance activity could not be found
	 */
	@Override
	public MaintenanceActivity fetchMaintenanceActivityByUuidAndCompanyId(
		String uuid, long companyId) {

		return maintenanceActivityPersistence.fetchByUuid_C_First(
			uuid, companyId, null);
	}

	/**
	 * Returns the maintenance activity with the primary key.
	 *
	 * @param maintenanceactivityId the primary key of the maintenance activity
	 * @return the maintenance activity
	 * @throws PortalException if a maintenance activity with the primary key could not be found
	 */
	@Override
	public MaintenanceActivity getMaintenanceActivity(
			long maintenanceactivityId)
		throws PortalException {

		return maintenanceActivityPersistence.findByPrimaryKey(
			maintenanceactivityId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			maintenanceActivityLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(MaintenanceActivity.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"maintenanceactivityId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			maintenanceActivityLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			MaintenanceActivity.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"maintenanceactivityId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			maintenanceActivityLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(MaintenanceActivity.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"maintenanceactivityId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod
				<MaintenanceActivity>() {

				@Override
				public void performAction(
						MaintenanceActivity maintenanceActivity)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, maintenanceActivity);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(
					MaintenanceActivity.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return maintenanceActivityPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return maintenanceActivityLocalService.deleteMaintenanceActivity(
			(MaintenanceActivity)persistedModel);
	}

	public BasePersistence<MaintenanceActivity> getBasePersistence() {
		return maintenanceActivityPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return maintenanceActivityPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns the maintenance activity with the matching UUID and company.
	 *
	 * @param uuid the maintenance activity's UUID
	 * @param companyId the primary key of the company
	 * @return the matching maintenance activity
	 * @throws PortalException if a matching maintenance activity could not be found
	 */
	@Override
	public MaintenanceActivity getMaintenanceActivityByUuidAndCompanyId(
			String uuid, long companyId)
		throws PortalException {

		return maintenanceActivityPersistence.findByUuid_C_First(
			uuid, companyId, null);
	}

	/**
	 * Returns a range of all the maintenance activities.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.everis.rec.maintenanceactivity.model.impl.MaintenanceActivityModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of maintenance activities
	 * @param end the upper bound of the range of maintenance activities (not inclusive)
	 * @return the range of maintenance activities
	 */
	@Override
	public List<MaintenanceActivity> getMaintenanceActivities(
		int start, int end) {

		return maintenanceActivityPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of maintenance activities.
	 *
	 * @return the number of maintenance activities
	 */
	@Override
	public int getMaintenanceActivitiesCount() {
		return maintenanceActivityPersistence.countAll();
	}

	/**
	 * Updates the maintenance activity in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect MaintenanceActivityLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param maintenanceActivity the maintenance activity
	 * @return the maintenance activity that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public MaintenanceActivity updateMaintenanceActivity(
		MaintenanceActivity maintenanceActivity) {

		return maintenanceActivityPersistence.update(maintenanceActivity);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			MaintenanceActivityLocalService.class,
			IdentifiableOSGiService.class, PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		maintenanceActivityLocalService =
			(MaintenanceActivityLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return MaintenanceActivityLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return MaintenanceActivity.class;
	}

	protected String getModelClassName() {
		return MaintenanceActivity.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				maintenanceActivityPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	protected MaintenanceActivityLocalService maintenanceActivityLocalService;

	@Reference
	protected MaintenanceActivityPersistence maintenanceActivityPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}