/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.everis.rec.ddl.journal.article.model;

import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DDL_JournalArticle service. Represents a row in the &quot;rec_ddl_journal_article&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.everis.rec.ddl.journal.article.model.impl.DDL_JournalArticleModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.everis.rec.ddl.journal.article.model.impl.DDL_JournalArticleImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DDL_JournalArticle
 * @generated
 */
@ProviderType
public interface DDL_JournalArticleModel extends BaseModel<DDL_JournalArticle> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ddl_ journal article model instance should use the {@link DDL_JournalArticle} interface instead.
	 */

	/**
	 * Returns the primary key of this ddl_ journal article.
	 *
	 * @return the primary key of this ddl_ journal article
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ddl_ journal article.
	 *
	 * @param primaryKey the primary key of this ddl_ journal article
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ddl record set ID of this ddl_ journal article.
	 *
	 * @return the ddl record set ID of this ddl_ journal article
	 */
	public long getDdlRecordSetId();

	/**
	 * Sets the ddl record set ID of this ddl_ journal article.
	 *
	 * @param ddlRecordSetId the ddl record set ID of this ddl_ journal article
	 */
	public void setDdlRecordSetId(long ddlRecordSetId);

	/**
	 * Returns the journal resource prim key of this ddl_ journal article.
	 *
	 * @return the journal resource prim key of this ddl_ journal article
	 */
	public long getJournalResourcePrimKey();

	/**
	 * Sets the journal resource prim key of this ddl_ journal article.
	 *
	 * @param journalResourcePrimKey the journal resource prim key of this ddl_ journal article
	 */
	public void setJournalResourcePrimKey(long journalResourcePrimKey);

}