/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.everis.rec.service.activity.logs.model.impl;

import com.everis.rec.service.activity.logs.model.RecLog;
import com.everis.rec.service.activity.logs.service.RecLogLocalServiceUtil;

/**
 * The extended model base implementation for the RecLog service. Represents a row in the &quot;ACTIVITY_RecLog&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RecLogImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RecLogImpl
 * @see RecLog
 * @generated
 */
public abstract class RecLogBaseImpl extends RecLogModelImpl implements RecLog {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a rec log model instance should use the <code>RecLog</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			RecLogLocalServiceUtil.addRecLog(this);
		}
		else {
			RecLogLocalServiceUtil.updateRecLog(this);
		}
	}

}