/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.everis.messages.service.builder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Messages service. Represents a row in the &quot;rec_messages&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.everis.messages.service.builder.model.impl.MessagesModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.everis.messages.service.builder.model.impl.MessagesImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Messages
 * @generated
 */
@ProviderType
public interface MessagesModel
	extends BaseModel<Messages>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a messages model instance should use the {@link Messages} interface instead.
	 */

	/**
	 * Returns the primary key of this messages.
	 *
	 * @return the primary key of this messages
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this messages.
	 *
	 * @param primaryKey the primary key of this messages
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this messages.
	 *
	 * @return the uuid of this messages
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this messages.
	 *
	 * @param uuid the uuid of this messages
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the notification engine ID of this messages.
	 *
	 * @return the notification engine ID of this messages
	 */
	public long getNotificationEngineId();

	/**
	 * Sets the notification engine ID of this messages.
	 *
	 * @param notificationEngineId the notification engine ID of this messages
	 */
	public void setNotificationEngineId(long notificationEngineId);

	/**
	 * Returns the group ID of this messages.
	 *
	 * @return the group ID of this messages
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this messages.
	 *
	 * @param groupId the group ID of this messages
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this messages.
	 *
	 * @return the company ID of this messages
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this messages.
	 *
	 * @param companyId the company ID of this messages
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this messages.
	 *
	 * @return the user ID of this messages
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this messages.
	 *
	 * @param userId the user ID of this messages
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this messages.
	 *
	 * @return the user uuid of this messages
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this messages.
	 *
	 * @param userUuid the user uuid of this messages
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this messages.
	 *
	 * @return the user name of this messages
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this messages.
	 *
	 * @param userName the user name of this messages
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this messages.
	 *
	 * @return the create date of this messages
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this messages.
	 *
	 * @param createDate the create date of this messages
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this messages.
	 *
	 * @return the modified date of this messages
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this messages.
	 *
	 * @param modifiedDate the modified date of this messages
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this messages.
	 *
	 * @return the name of this messages
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this messages.
	 *
	 * @param name the name of this messages
	 */
	public void setName(String name);

	/**
	 * Returns the subject of this messages.
	 *
	 * @return the subject of this messages
	 */
	@AutoEscape
	public String getSubject();

	/**
	 * Sets the subject of this messages.
	 *
	 * @param subject the subject of this messages
	 */
	public void setSubject(String subject);

	/**
	 * Returns the body of this messages.
	 *
	 * @return the body of this messages
	 */
	@AutoEscape
	public String getBody();

	/**
	 * Sets the body of this messages.
	 *
	 * @param body the body of this messages
	 */
	public void setBody(String body);

	/**
	 * Returns the status of this messages.
	 *
	 * @return the status of this messages
	 */
	public boolean getStatus();

	/**
	 * Returns <code>true</code> if this messages is status.
	 *
	 * @return <code>true</code> if this messages is status; <code>false</code> otherwise
	 */
	public boolean isStatus();

	/**
	 * Sets whether this messages is status.
	 *
	 * @param status the status of this messages
	 */
	public void setStatus(boolean status);

	/**
	 * Returns the tags of this messages.
	 *
	 * @return the tags of this messages
	 */
	@AutoEscape
	public String getTags();

	/**
	 * Sets the tags of this messages.
	 *
	 * @param tags the tags of this messages
	 */
	public void setTags(String tags);

}