/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.everis.rec.ddl.journal.article.model.impl;

import com.everis.rec.ddl.journal.article.model.DDL_JournalArticle;
import com.everis.rec.ddl.journal.article.service.DDL_JournalArticleLocalServiceUtil;

/**
 * The extended model base implementation for the DDL_JournalArticle service. Represents a row in the &quot;rec_ddl_journal_article&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DDL_JournalArticleImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DDL_JournalArticleImpl
 * @see DDL_JournalArticle
 * @generated
 */
public abstract class DDL_JournalArticleBaseImpl
	extends DDL_JournalArticleModelImpl implements DDL_JournalArticle {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ddl_ journal article model instance should use the <code>DDL_JournalArticle</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			DDL_JournalArticleLocalServiceUtil.addDDL_JournalArticle(this);
		}
		else {
			DDL_JournalArticleLocalServiceUtil.updateDDL_JournalArticle(this);
		}
	}

}